/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */
/* Source: protocol/waywallen_ipc_v1.xml */

#ifndef WAYWALLEN_PROTO_H
#define WAYWALLEN_PROTO_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WW_PROTOCOL_NAME    "waywallen-ipc-v1"
#define WW_PROTOCOL_VERSION 1

/* --- Shared primitive types --- */

typedef struct ww_rect {
    float x;
    float y;
    float w;
    float h;
} ww_rect_t;

typedef struct ww_array_u32 {
    uint32_t count;
    uint32_t *data;    /* heap-allocated by decoder; NULL if count==0 */
} ww_array_u32_t;

typedef struct ww_array_u64 {
    uint32_t count;
    uint64_t *data;
} ww_array_u64_t;

typedef struct ww_array_i32 {
    uint32_t count;
    int32_t *data;
} ww_array_i32_t;

typedef struct ww_array_i64 {
    uint32_t count;
    int64_t *data;
} ww_array_i64_t;

typedef struct ww_array_f32 {
    uint32_t count;
    float *data;
} ww_array_f32_t;

typedef struct ww_array_f64 {
    uint32_t count;
    double *data;
} ww_array_f64_t;

typedef struct ww_array_string {
    uint32_t count;
    char **data;       /* each entry NUL-terminated, heap-allocated */
} ww_array_string_t;

typedef struct ww_kv {
    char *key;
    char *value;
} ww_kv_t;

typedef struct ww_kv_list {
    uint32_t count;
    ww_kv_t *data;
} ww_kv_list_t;

/* --- Codec buffer + return codes --- */

typedef struct ww_buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} ww_buf_t;

/* Return codes: 0 = success, negative = -errno-ish. */
#define WW_OK                  0
#define WW_ERR_SHORT           (-1)   /* buffer truncated */
#define WW_ERR_BAD_STRING      (-2)   /* malformed length-prefixed string */
#define WW_ERR_BAD_ARRAY       (-3)   /* array length overflow */
#define WW_ERR_TRAILING        (-4)   /* unexpected trailing bytes */
#define WW_ERR_UNKNOWN_OPCODE  (-5)
#define WW_ERR_NOMEM           (-6)
#define WW_ERR_OVERFLOW        (-7)   /* frame bigger than u16 can address */

/* --- Opcodes --- */

typedef enum ww_request_op {
    WW_REQ_HELLO = 1,
    WW_REQ_LOAD_SCENE = 2,
    WW_REQ_PLAY = 3,
    WW_REQ_PAUSE = 4,
    WW_REQ_MOUSE = 5,
    WW_REQ_SET_FPS = 6,
    WW_REQ_SHUTDOWN = 7,
} ww_request_op_t;

typedef enum ww_event_op {
    WW_EVT_READY = 1,
    WW_EVT_BIND_BUFFERS = 2,
    WW_EVT_FRAME_READY = 3,
    WW_EVT_ERROR = 4,
} ww_event_op_t;

typedef struct ww_req_hello_t {
    char *client;
    uint32_t version;
} ww_req_hello_t;

typedef struct ww_req_load_scene_t {
    char *pkg;
    char *assets;
    uint32_t fps;
    uint32_t width;
    uint32_t height;
} ww_req_load_scene_t;

typedef struct ww_req_play_t {
    int _empty; /* C forbids empty structs */
} ww_req_play_t;

typedef struct ww_req_pause_t {
    int _empty; /* C forbids empty structs */
} ww_req_pause_t;

typedef struct ww_req_mouse_t {
    double x;
    double y;
} ww_req_mouse_t;

typedef struct ww_req_set_fps_t {
    uint32_t fps;
} ww_req_set_fps_t;

typedef struct ww_req_shutdown_t {
    int _empty; /* C forbids empty structs */
} ww_req_shutdown_t;

typedef struct ww_evt_ready_t {
    int _empty; /* C forbids empty structs */
} ww_evt_ready_t;

typedef struct ww_evt_bind_buffers_t {
    uint32_t count;
    uint32_t fourcc;
    uint32_t width;
    uint32_t height;
    uint32_t stride;
    uint64_t modifier;
    uint64_t plane_offset;
    ww_array_u64_t sizes;
} ww_evt_bind_buffers_t;

typedef struct ww_evt_frame_ready_t {
    uint32_t image_index;
    uint64_t seq;
    uint64_t ts_ns;
} ww_evt_frame_ready_t;

typedef struct ww_evt_error_t {
    char *msg;
} ww_evt_error_t;

/* --- Per-message functions ---
 * encode:        append wire body to `out` (header is the caller's job)
 * decode:        consume `len` bytes; on success owns heap allocations
 * free:          release any heap fields the decoder populated
 * expected_fds:  how many SCM_RIGHTS fds the wire frame must carry
 */

int  ww_req_hello_encode(const ww_req_hello_t *m, ww_buf_t *out);
int  ww_req_hello_decode(const uint8_t *buf, size_t len, ww_req_hello_t *out);
void ww_req_hello_free(ww_req_hello_t *m);
uint32_t ww_req_hello_expected_fds(const ww_req_hello_t *m);

int  ww_req_load_scene_encode(const ww_req_load_scene_t *m, ww_buf_t *out);
int  ww_req_load_scene_decode(const uint8_t *buf, size_t len, ww_req_load_scene_t *out);
void ww_req_load_scene_free(ww_req_load_scene_t *m);
uint32_t ww_req_load_scene_expected_fds(const ww_req_load_scene_t *m);

int  ww_req_play_encode(const ww_req_play_t *m, ww_buf_t *out);
int  ww_req_play_decode(const uint8_t *buf, size_t len, ww_req_play_t *out);
void ww_req_play_free(ww_req_play_t *m);
uint32_t ww_req_play_expected_fds(const ww_req_play_t *m);

int  ww_req_pause_encode(const ww_req_pause_t *m, ww_buf_t *out);
int  ww_req_pause_decode(const uint8_t *buf, size_t len, ww_req_pause_t *out);
void ww_req_pause_free(ww_req_pause_t *m);
uint32_t ww_req_pause_expected_fds(const ww_req_pause_t *m);

int  ww_req_mouse_encode(const ww_req_mouse_t *m, ww_buf_t *out);
int  ww_req_mouse_decode(const uint8_t *buf, size_t len, ww_req_mouse_t *out);
void ww_req_mouse_free(ww_req_mouse_t *m);
uint32_t ww_req_mouse_expected_fds(const ww_req_mouse_t *m);

int  ww_req_set_fps_encode(const ww_req_set_fps_t *m, ww_buf_t *out);
int  ww_req_set_fps_decode(const uint8_t *buf, size_t len, ww_req_set_fps_t *out);
void ww_req_set_fps_free(ww_req_set_fps_t *m);
uint32_t ww_req_set_fps_expected_fds(const ww_req_set_fps_t *m);

int  ww_req_shutdown_encode(const ww_req_shutdown_t *m, ww_buf_t *out);
int  ww_req_shutdown_decode(const uint8_t *buf, size_t len, ww_req_shutdown_t *out);
void ww_req_shutdown_free(ww_req_shutdown_t *m);
uint32_t ww_req_shutdown_expected_fds(const ww_req_shutdown_t *m);

int  ww_evt_ready_encode(const ww_evt_ready_t *m, ww_buf_t *out);
int  ww_evt_ready_decode(const uint8_t *buf, size_t len, ww_evt_ready_t *out);
void ww_evt_ready_free(ww_evt_ready_t *m);
uint32_t ww_evt_ready_expected_fds(const ww_evt_ready_t *m);

int  ww_evt_bind_buffers_encode(const ww_evt_bind_buffers_t *m, ww_buf_t *out);
int  ww_evt_bind_buffers_decode(const uint8_t *buf, size_t len, ww_evt_bind_buffers_t *out);
void ww_evt_bind_buffers_free(ww_evt_bind_buffers_t *m);
uint32_t ww_evt_bind_buffers_expected_fds(const ww_evt_bind_buffers_t *m);

int  ww_evt_frame_ready_encode(const ww_evt_frame_ready_t *m, ww_buf_t *out);
int  ww_evt_frame_ready_decode(const uint8_t *buf, size_t len, ww_evt_frame_ready_t *out);
void ww_evt_frame_ready_free(ww_evt_frame_ready_t *m);
uint32_t ww_evt_frame_ready_expected_fds(const ww_evt_frame_ready_t *m);

int  ww_evt_error_encode(const ww_evt_error_t *m, ww_buf_t *out);
int  ww_evt_error_decode(const uint8_t *buf, size_t len, ww_evt_error_t *out);
void ww_evt_error_free(ww_evt_error_t *m);
uint32_t ww_evt_error_expected_fds(const ww_evt_error_t *m);

/* --- Output buffer helpers --- */
void ww_buf_init(ww_buf_t *b);
void ww_buf_free(ww_buf_t *b);
int  ww_buf_reserve(ww_buf_t *b, size_t additional);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WAYWALLEN_PROTO_H */
