/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */
/* Source: protocol/waywallen_ipc_v3.xml */

#ifndef WAYWALLEN_PROTO_H
#define WAYWALLEN_PROTO_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WW_PROTOCOL_NAME    "waywallen-ipc-v3"
#define WW_PROTOCOL_VERSION 3

#ifndef WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED
#define WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED

/* --- Shared primitive value types --- */

typedef struct ww_rect {
    float x;
    float y;
    float w;
    float h;
} ww_rect_t;

typedef struct ww_array_u32 {
    uint32_t count;
    uint32_t *data;    /* heap-allocated by decoder; NULL if count==0 */
} ww_array_u32_t;

typedef struct ww_array_u64 {
    uint32_t count;
    uint64_t *data;
} ww_array_u64_t;

typedef struct ww_array_i32 {
    uint32_t count;
    int32_t *data;
} ww_array_i32_t;

typedef struct ww_array_i64 {
    uint32_t count;
    int64_t *data;
} ww_array_i64_t;

typedef struct ww_array_f32 {
    uint32_t count;
    float *data;
} ww_array_f32_t;

typedef struct ww_array_f64 {
    uint32_t count;
    double *data;
} ww_array_f64_t;

typedef struct ww_array_string {
    uint32_t count;
    char **data;       /* each entry NUL-terminated, heap-allocated */
} ww_array_string_t;

typedef struct ww_kv {
    char *key;
    char *value;
} ww_kv_t;

typedef struct ww_kv_list {
    uint32_t count;
    ww_kv_t *data;
} ww_kv_list_t;

#endif /* WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED */

/* --- Codec buffer + return codes --- */

typedef struct ww_buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} ww_buf_t;

/* Return codes: 0 = success, negative = -errno-ish. */
#define WW_OK                  0
#define WW_ERR_SHORT           (-1)   /* buffer truncated */
#define WW_ERR_BAD_STRING      (-2)   /* malformed length-prefixed string */
#define WW_ERR_BAD_ARRAY       (-3)   /* array length overflow */
#define WW_ERR_TRAILING        (-4)   /* unexpected trailing bytes */
#define WW_ERR_UNKNOWN_OPCODE  (-5)
#define WW_ERR_NOMEM           (-6)
#define WW_ERR_OVERFLOW        (-7)   /* frame bigger than u16 can address */
#define WW_ERR_BAD_BOOL        (-8)   /* boolean is not canonical 0/1 */
#define WW_ERR_BAD_ENUM        (-9)   /* enum value is not declared */

#ifndef WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED
#define WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED

typedef enum waywallen_pointer_button_state {
    WAYWALLEN_POINTER_BUTTON_STATE_RELEASED = 0,
    WAYWALLEN_POINTER_BUTTON_STATE_PRESSED = 1,
} waywallen_pointer_button_state_t;

typedef enum waywallen_pointer_axis_source {
    WAYWALLEN_POINTER_AXIS_SOURCE_WHEEL = 0,
    WAYWALLEN_POINTER_AXIS_SOURCE_FINGER = 1,
    WAYWALLEN_POINTER_AXIS_SOURCE_CONTINUOUS = 2,
} waywallen_pointer_axis_source_t;

typedef enum waywallen_media_playback_state {
    WAYWALLEN_MEDIA_PLAYBACK_STATE_STOPPED = 0,
    WAYWALLEN_MEDIA_PLAYBACK_STATE_PLAYING = 1,
    WAYWALLEN_MEDIA_PLAYBACK_STATE_PAUSED = 2,
} waywallen_media_playback_state_t;

typedef enum waywallen_event_subscription_status {
    WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_APPLIED = 0,
    WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_INVALID = 1,
    WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_STALE_REVISION = 2,
    WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_REVISION_CONFLICT = 3,
    WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_LIMIT_EXCEEDED = 4,
} waywallen_event_subscription_status_t;

typedef enum waywallen_buffer_path {
    WAYWALLEN_BUFFER_PATH_OPTIMIZED_SAME_DEVICE = 0,
    WAYWALLEN_BUFFER_PATH_OPTIMIZED_SAME_VENDOR = 1,
    WAYWALLEN_BUFFER_PATH_COMPAT_LINEAR = 2,
    WAYWALLEN_BUFFER_PATH_COMPAT_CPU_READBACK = 3,
} waywallen_buffer_path_t;

typedef enum waywallen_buffer_memory_source {
    WAYWALLEN_BUFFER_MEMORY_SOURCE_GPU_NATIVE = 0,
    WAYWALLEN_BUFFER_MEMORY_SOURCE_GPU_LINEAR = 1,
    WAYWALLEN_BUFFER_MEMORY_SOURCE_DMABUF_HEAP = 2,
} waywallen_buffer_memory_source_t;

typedef enum waywallen_buffer_allocation_failure_kind {
    WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_ALLOCATOR_REJECTED = 0,
    WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_RESOURCE_EXHAUSTED = 1,
    WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_UNSUPPORTED = 2,
    WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_OTHER = 3,
} waywallen_buffer_allocation_failure_kind_t;

typedef struct waywallen_audio_stream_format {
    uint32_t sample_rate_hz;
    uint32_t channels;
} waywallen_audio_stream_format_t;

typedef struct waywallen_audio_window {
    uint64_t subscription_revision;
    uint64_t generation;
    uint64_t sequence;
    uint64_t captured_at_ns;
    uint64_t end_sample_frame;
    waywallen_audio_stream_format_t format;
    uint32_t frames;
    uint32_t flags;
    ww_array_f32_t samples;
} waywallen_audio_window_t;

typedef struct waywallen_buffer_format {
    uint32_t fourcc;
    uint64_t modifier;
    uint32_t plane_count;
} waywallen_buffer_format_t;

typedef struct waywallen_bind_failure {
    waywallen_buffer_format_t format;
    waywallen_buffer_allocation_failure_kind_t kind;
    char * message;
} waywallen_bind_failure_t;

typedef struct waywallen_buffer_directive {
    waywallen_buffer_format_t format;
    uint32_t sync_mode;
    uint32_t color;
    uint32_t mem_hint;
    uint32_t count;
    waywallen_buffer_path_t path;
    waywallen_buffer_memory_source_t memory_source;
} waywallen_buffer_directive_t;

typedef struct waywallen_extent {
    uint32_t width;
    uint32_t height;
} waywallen_extent_t;

typedef struct waywallen_buffer_pool {
    uint64_t generation;
    uint32_t flags;
    uint32_t count;
    waywallen_buffer_format_t format;
    waywallen_extent_t extent;
    ww_array_u32_t stride;
    ww_array_u32_t plane_offset;
    ww_array_u64_t size;
} waywallen_buffer_pool_t;

typedef struct waywallen_control_transition {
    uint32_t fade_ms;
} waywallen_control_transition_t;

typedef struct waywallen_drm_node {
    uint32_t major;
    uint32_t minor;
} waywallen_drm_node_t;

typedef struct waywallen_event_subscription {
    uint64_t revision;
    ww_array_string_t kinds;
} waywallen_event_subscription_t;

typedef struct waywallen_event_subscription_result {
    uint64_t revision;
    waywallen_event_subscription_status_t status;
    ww_array_string_t kinds;
    char * reason;
} waywallen_event_subscription_result_t;

typedef struct waywallen_frame {
    uint32_t image_index;
    uint64_t sequence;
    uint64_t produced_at_ns;
    uint64_t release_point;
} waywallen_frame_t;

typedef struct waywallen_init_rejection {
    uint32_t received_protocol_version;
    uint32_t supported_protocol_version;
    uint32_t received_spawn_version;
    uint32_t supported_spawn_version;
    char * reason;
} waywallen_init_rejection_t;

typedef struct waywallen_mpris_snapshot {
    waywallen_media_playback_state_t state;
    char * title;
    char * artist;
    char * album;
    char * album_artist;
    char * art_url;
    char * previous_art_url;
} waywallen_mpris_snapshot_t;

typedef struct waywallen_pointer_axis {
    float x;
    float y;
    float delta_x;
    float delta_y;
    waywallen_pointer_axis_source_t source;
    uint64_t timestamp_us;
    uint32_t modifiers;
} waywallen_pointer_axis_t;

typedef struct waywallen_pointer_button {
    float x;
    float y;
    uint32_t button;
    waywallen_pointer_button_state_t state;
    uint64_t timestamp_us;
    uint32_t modifiers;
} waywallen_pointer_button_t;

typedef struct waywallen_pointer_motion {
    float x;
    float y;
    uint64_t timestamp_us;
    uint32_t modifiers;
} waywallen_pointer_motion_t;

typedef struct waywallen_producer_capabilities {
    ww_array_u32_t fourccs;
    ww_array_u32_t mod_counts;
    ww_array_u64_t modifiers;
    ww_array_u32_t plane_counts;
    ww_array_u32_t device_uuid;
    ww_array_u32_t driver_uuid;
    waywallen_drm_node_t drm_node;
    uint32_t mem_hints;
    uint32_t sync_caps;
    uint32_t color_caps;
    waywallen_extent_t max_extent;
} waywallen_producer_capabilities_t;

typedef struct waywallen_renderer_init {
    uint32_t protocol_version;
    uint32_t spawn_version;
    ww_kv_list_t settings;
    char * user_properties;
    uint32_t display_width;
    uint32_t display_height;
} waywallen_renderer_init_t;

typedef struct waywallen_rgba_color {
    float r;
    float g;
    float b;
    float a;
} waywallen_rgba_color_t;

typedef struct waywallen_renderer_state {
    uint32_t fields;
    waywallen_rgba_color_t clear_color;
    ww_kv_list_t runtime_tags;
} waywallen_renderer_state_t;

#endif /* WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED */

/* --- Named value lifecycle --- */

void waywallen_audio_stream_format_free(waywallen_audio_stream_format_t *value);
void waywallen_audio_window_free(waywallen_audio_window_t *value);
void waywallen_buffer_format_free(waywallen_buffer_format_t *value);
void waywallen_bind_failure_free(waywallen_bind_failure_t *value);
void waywallen_buffer_directive_free(waywallen_buffer_directive_t *value);
void waywallen_extent_free(waywallen_extent_t *value);
void waywallen_buffer_pool_free(waywallen_buffer_pool_t *value);
void waywallen_control_transition_free(waywallen_control_transition_t *value);
void waywallen_drm_node_free(waywallen_drm_node_t *value);
void waywallen_event_subscription_free(waywallen_event_subscription_t *value);
void waywallen_event_subscription_result_free(waywallen_event_subscription_result_t *value);
void waywallen_frame_free(waywallen_frame_t *value);
void waywallen_init_rejection_free(waywallen_init_rejection_t *value);
void waywallen_mpris_snapshot_free(waywallen_mpris_snapshot_t *value);
void waywallen_pointer_axis_free(waywallen_pointer_axis_t *value);
void waywallen_pointer_button_free(waywallen_pointer_button_t *value);
void waywallen_pointer_motion_free(waywallen_pointer_motion_t *value);
void waywallen_producer_capabilities_free(waywallen_producer_capabilities_t *value);
void waywallen_renderer_init_free(waywallen_renderer_init_t *value);
void waywallen_rgba_color_free(waywallen_rgba_color_t *value);
void waywallen_renderer_state_free(waywallen_renderer_state_t *value);

/* --- Opcodes --- */

typedef enum ww_event_in_op {
    WW_EVT_IN_INIT = 1,
    WW_EVT_IN_SETTING_CHANGED = 2,
    WW_EVT_IN_PLAY = 3,
    WW_EVT_IN_PAUSE = 4,
    WW_EVT_IN_POINTER_MOTION = 5,
    WW_EVT_IN_SHUTDOWN = 6,
    WW_EVT_IN_NEGOTIATE_BUFFERS = 7,
    WW_EVT_IN_POINTER_BUTTON = 8,
    WW_EVT_IN_POINTER_AXIS = 9,
    WW_EVT_IN_MUTE = 10,
    WW_EVT_IN_UNMUTE = 11,
    WW_EVT_IN_MPRIS = 12,
    WW_EVT_IN_EVENT_SUBSCRIPTIONS_APPLIED = 13,
    WW_EVT_IN_AUDIO_WINDOW = 14,
    WW_EVT_IN_REQUEST_FRAME = 15,
} ww_event_in_op_t;

typedef enum ww_event_op {
    WW_EVT_READY = 1,
    WW_EVT_BIND_BUFFERS = 2,
    WW_EVT_FRAME_READY = 3,
    WW_EVT_ERROR = 4,
    WW_EVT_RELEASE_SYNCOBJ = 5,
    WW_EVT_FORMAT_CAPS = 6,
    WW_EVT_BIND_FAILED = 7,
    WW_EVT_INIT_NACK = 8,
    WW_EVT_REPORT_STATE = 9,
    WW_EVT_SET_EVENT_SUBSCRIPTIONS = 10,
} ww_event_op_t;

typedef struct ww_evt_in_init_t {
    waywallen_renderer_init_t config;
} ww_evt_in_init_t;

typedef struct ww_evt_in_setting_changed_t {
    ww_kv_list_t settings;
} ww_evt_in_setting_changed_t;

typedef struct ww_evt_in_play_t {
    waywallen_control_transition_t transition;
} ww_evt_in_play_t;

typedef struct ww_evt_in_pause_t {
    waywallen_control_transition_t transition;
} ww_evt_in_pause_t;

typedef struct ww_evt_in_pointer_motion_t {
    waywallen_pointer_motion_t event;
} ww_evt_in_pointer_motion_t;

typedef struct ww_evt_in_shutdown_t {
    int _empty; /* C forbids empty structs */
} ww_evt_in_shutdown_t;

typedef struct ww_evt_in_negotiate_buffers_t {
    waywallen_buffer_directive_t directive;
} ww_evt_in_negotiate_buffers_t;

typedef struct ww_evt_in_pointer_button_t {
    waywallen_pointer_button_t event;
} ww_evt_in_pointer_button_t;

typedef struct ww_evt_in_pointer_axis_t {
    waywallen_pointer_axis_t event;
} ww_evt_in_pointer_axis_t;

typedef struct ww_evt_in_mute_t {
    waywallen_control_transition_t transition;
} ww_evt_in_mute_t;

typedef struct ww_evt_in_unmute_t {
    waywallen_control_transition_t transition;
} ww_evt_in_unmute_t;

typedef struct ww_evt_in_mpris_t {
    waywallen_mpris_snapshot_t snapshot;
} ww_evt_in_mpris_t;

typedef struct ww_evt_in_event_subscriptions_applied_t {
    waywallen_event_subscription_result_t result;
} ww_evt_in_event_subscriptions_applied_t;

typedef struct ww_evt_in_audio_window_t {
    waywallen_audio_window_t window;
} ww_evt_in_audio_window_t;

typedef struct ww_evt_in_request_frame_t {
    int _empty; /* C forbids empty structs */
} ww_evt_in_request_frame_t;

typedef struct ww_evt_ready_t {
    waywallen_drm_node_t drm_node;
} ww_evt_ready_t;

typedef struct ww_evt_bind_buffers_t {
    waywallen_buffer_pool_t pool;
} ww_evt_bind_buffers_t;

typedef struct ww_evt_frame_ready_t {
    waywallen_frame_t frame;
} ww_evt_frame_ready_t;

typedef struct ww_evt_error_t {
    char *message;
} ww_evt_error_t;

typedef struct ww_evt_release_syncobj_t {
    int _empty; /* C forbids empty structs */
} ww_evt_release_syncobj_t;

typedef struct ww_evt_format_caps_t {
    waywallen_producer_capabilities_t capabilities;
} ww_evt_format_caps_t;

typedef struct ww_evt_bind_failed_t {
    waywallen_bind_failure_t failure;
} ww_evt_bind_failed_t;

typedef struct ww_evt_init_nack_t {
    waywallen_init_rejection_t rejection;
} ww_evt_init_nack_t;

typedef struct ww_evt_report_state_t {
    waywallen_renderer_state_t state;
} ww_evt_report_state_t;

typedef struct ww_evt_set_event_subscriptions_t {
    waywallen_event_subscription_t subscription;
} ww_evt_set_event_subscriptions_t;

/* --- Per-message functions ---
 * encode:        append wire body to `out` (header is the caller's job)
 * decode:        consume `len` bytes; on success owns heap allocations
 * free:          release any heap fields the decoder populated
 * expected_fds:  how many SCM_RIGHTS fds the wire frame must carry
 */

int  ww_evt_in_init_encode(const ww_evt_in_init_t *m, ww_buf_t *out);
int  ww_evt_in_init_decode(const uint8_t *buf, size_t len, ww_evt_in_init_t *out);
void ww_evt_in_init_free(ww_evt_in_init_t *m);
uint32_t ww_evt_in_init_expected_fds(const ww_evt_in_init_t *m);

int  ww_evt_in_setting_changed_encode(const ww_evt_in_setting_changed_t *m, ww_buf_t *out);
int  ww_evt_in_setting_changed_decode(const uint8_t *buf, size_t len, ww_evt_in_setting_changed_t *out);
void ww_evt_in_setting_changed_free(ww_evt_in_setting_changed_t *m);
uint32_t ww_evt_in_setting_changed_expected_fds(const ww_evt_in_setting_changed_t *m);

int  ww_evt_in_play_encode(const ww_evt_in_play_t *m, ww_buf_t *out);
int  ww_evt_in_play_decode(const uint8_t *buf, size_t len, ww_evt_in_play_t *out);
void ww_evt_in_play_free(ww_evt_in_play_t *m);
uint32_t ww_evt_in_play_expected_fds(const ww_evt_in_play_t *m);

int  ww_evt_in_pause_encode(const ww_evt_in_pause_t *m, ww_buf_t *out);
int  ww_evt_in_pause_decode(const uint8_t *buf, size_t len, ww_evt_in_pause_t *out);
void ww_evt_in_pause_free(ww_evt_in_pause_t *m);
uint32_t ww_evt_in_pause_expected_fds(const ww_evt_in_pause_t *m);

int  ww_evt_in_pointer_motion_encode(const ww_evt_in_pointer_motion_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_motion_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_motion_t *out);
void ww_evt_in_pointer_motion_free(ww_evt_in_pointer_motion_t *m);
uint32_t ww_evt_in_pointer_motion_expected_fds(const ww_evt_in_pointer_motion_t *m);

int  ww_evt_in_shutdown_encode(const ww_evt_in_shutdown_t *m, ww_buf_t *out);
int  ww_evt_in_shutdown_decode(const uint8_t *buf, size_t len, ww_evt_in_shutdown_t *out);
void ww_evt_in_shutdown_free(ww_evt_in_shutdown_t *m);
uint32_t ww_evt_in_shutdown_expected_fds(const ww_evt_in_shutdown_t *m);

int  ww_evt_in_negotiate_buffers_encode(const ww_evt_in_negotiate_buffers_t *m, ww_buf_t *out);
int  ww_evt_in_negotiate_buffers_decode(const uint8_t *buf, size_t len, ww_evt_in_negotiate_buffers_t *out);
void ww_evt_in_negotiate_buffers_free(ww_evt_in_negotiate_buffers_t *m);
uint32_t ww_evt_in_negotiate_buffers_expected_fds(const ww_evt_in_negotiate_buffers_t *m);

int  ww_evt_in_pointer_button_encode(const ww_evt_in_pointer_button_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_button_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_button_t *out);
void ww_evt_in_pointer_button_free(ww_evt_in_pointer_button_t *m);
uint32_t ww_evt_in_pointer_button_expected_fds(const ww_evt_in_pointer_button_t *m);

int  ww_evt_in_pointer_axis_encode(const ww_evt_in_pointer_axis_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_axis_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_axis_t *out);
void ww_evt_in_pointer_axis_free(ww_evt_in_pointer_axis_t *m);
uint32_t ww_evt_in_pointer_axis_expected_fds(const ww_evt_in_pointer_axis_t *m);

int  ww_evt_in_mute_encode(const ww_evt_in_mute_t *m, ww_buf_t *out);
int  ww_evt_in_mute_decode(const uint8_t *buf, size_t len, ww_evt_in_mute_t *out);
void ww_evt_in_mute_free(ww_evt_in_mute_t *m);
uint32_t ww_evt_in_mute_expected_fds(const ww_evt_in_mute_t *m);

int  ww_evt_in_unmute_encode(const ww_evt_in_unmute_t *m, ww_buf_t *out);
int  ww_evt_in_unmute_decode(const uint8_t *buf, size_t len, ww_evt_in_unmute_t *out);
void ww_evt_in_unmute_free(ww_evt_in_unmute_t *m);
uint32_t ww_evt_in_unmute_expected_fds(const ww_evt_in_unmute_t *m);

int  ww_evt_in_mpris_encode(const ww_evt_in_mpris_t *m, ww_buf_t *out);
int  ww_evt_in_mpris_decode(const uint8_t *buf, size_t len, ww_evt_in_mpris_t *out);
void ww_evt_in_mpris_free(ww_evt_in_mpris_t *m);
uint32_t ww_evt_in_mpris_expected_fds(const ww_evt_in_mpris_t *m);

int  ww_evt_in_event_subscriptions_applied_encode(const ww_evt_in_event_subscriptions_applied_t *m, ww_buf_t *out);
int  ww_evt_in_event_subscriptions_applied_decode(const uint8_t *buf, size_t len, ww_evt_in_event_subscriptions_applied_t *out);
void ww_evt_in_event_subscriptions_applied_free(ww_evt_in_event_subscriptions_applied_t *m);
uint32_t ww_evt_in_event_subscriptions_applied_expected_fds(const ww_evt_in_event_subscriptions_applied_t *m);

int  ww_evt_in_audio_window_encode(const ww_evt_in_audio_window_t *m, ww_buf_t *out);
int  ww_evt_in_audio_window_decode(const uint8_t *buf, size_t len, ww_evt_in_audio_window_t *out);
void ww_evt_in_audio_window_free(ww_evt_in_audio_window_t *m);
uint32_t ww_evt_in_audio_window_expected_fds(const ww_evt_in_audio_window_t *m);

int  ww_evt_in_request_frame_encode(const ww_evt_in_request_frame_t *m, ww_buf_t *out);
int  ww_evt_in_request_frame_decode(const uint8_t *buf, size_t len, ww_evt_in_request_frame_t *out);
void ww_evt_in_request_frame_free(ww_evt_in_request_frame_t *m);
uint32_t ww_evt_in_request_frame_expected_fds(const ww_evt_in_request_frame_t *m);

int  ww_evt_ready_encode(const ww_evt_ready_t *m, ww_buf_t *out);
int  ww_evt_ready_decode(const uint8_t *buf, size_t len, ww_evt_ready_t *out);
void ww_evt_ready_free(ww_evt_ready_t *m);
uint32_t ww_evt_ready_expected_fds(const ww_evt_ready_t *m);

int  ww_evt_bind_buffers_encode(const ww_evt_bind_buffers_t *m, ww_buf_t *out);
int  ww_evt_bind_buffers_decode(const uint8_t *buf, size_t len, ww_evt_bind_buffers_t *out);
void ww_evt_bind_buffers_free(ww_evt_bind_buffers_t *m);
uint32_t ww_evt_bind_buffers_expected_fds(const ww_evt_bind_buffers_t *m);

int  ww_evt_frame_ready_encode(const ww_evt_frame_ready_t *m, ww_buf_t *out);
int  ww_evt_frame_ready_decode(const uint8_t *buf, size_t len, ww_evt_frame_ready_t *out);
void ww_evt_frame_ready_free(ww_evt_frame_ready_t *m);
uint32_t ww_evt_frame_ready_expected_fds(const ww_evt_frame_ready_t *m);

int  ww_evt_error_encode(const ww_evt_error_t *m, ww_buf_t *out);
int  ww_evt_error_decode(const uint8_t *buf, size_t len, ww_evt_error_t *out);
void ww_evt_error_free(ww_evt_error_t *m);
uint32_t ww_evt_error_expected_fds(const ww_evt_error_t *m);

int  ww_evt_release_syncobj_encode(const ww_evt_release_syncobj_t *m, ww_buf_t *out);
int  ww_evt_release_syncobj_decode(const uint8_t *buf, size_t len, ww_evt_release_syncobj_t *out);
void ww_evt_release_syncobj_free(ww_evt_release_syncobj_t *m);
uint32_t ww_evt_release_syncobj_expected_fds(const ww_evt_release_syncobj_t *m);

int  ww_evt_format_caps_encode(const ww_evt_format_caps_t *m, ww_buf_t *out);
int  ww_evt_format_caps_decode(const uint8_t *buf, size_t len, ww_evt_format_caps_t *out);
void ww_evt_format_caps_free(ww_evt_format_caps_t *m);
uint32_t ww_evt_format_caps_expected_fds(const ww_evt_format_caps_t *m);

int  ww_evt_bind_failed_encode(const ww_evt_bind_failed_t *m, ww_buf_t *out);
int  ww_evt_bind_failed_decode(const uint8_t *buf, size_t len, ww_evt_bind_failed_t *out);
void ww_evt_bind_failed_free(ww_evt_bind_failed_t *m);
uint32_t ww_evt_bind_failed_expected_fds(const ww_evt_bind_failed_t *m);

int  ww_evt_init_nack_encode(const ww_evt_init_nack_t *m, ww_buf_t *out);
int  ww_evt_init_nack_decode(const uint8_t *buf, size_t len, ww_evt_init_nack_t *out);
void ww_evt_init_nack_free(ww_evt_init_nack_t *m);
uint32_t ww_evt_init_nack_expected_fds(const ww_evt_init_nack_t *m);

int  ww_evt_report_state_encode(const ww_evt_report_state_t *m, ww_buf_t *out);
int  ww_evt_report_state_decode(const uint8_t *buf, size_t len, ww_evt_report_state_t *out);
void ww_evt_report_state_free(ww_evt_report_state_t *m);
uint32_t ww_evt_report_state_expected_fds(const ww_evt_report_state_t *m);

int  ww_evt_set_event_subscriptions_encode(const ww_evt_set_event_subscriptions_t *m, ww_buf_t *out);
int  ww_evt_set_event_subscriptions_decode(const uint8_t *buf, size_t len, ww_evt_set_event_subscriptions_t *out);
void ww_evt_set_event_subscriptions_free(ww_evt_set_event_subscriptions_t *m);
uint32_t ww_evt_set_event_subscriptions_expected_fds(const ww_evt_set_event_subscriptions_t *m);

/* --- Output buffer helpers --- */
void ww_buf_init(ww_buf_t *b);
void ww_buf_free(ww_buf_t *b);
int  ww_buf_reserve(ww_buf_t *b, size_t additional);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WAYWALLEN_PROTO_H */
