/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */
/* clang-format off */
/* Source: protocol/waywallen_ipc_v3.xml */

#include "waywallen-bridge/ipc_v3.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Some wire helpers are unused for the current protocol revision (e.g.
 * no i64 args today) but we emit them unconditionally so future
 * revisions can add those types without touching the codegen.
 *
 * -Wtype-limits is silenced for the same reason: array-length overflow
 * guards compare `uint32_t > SIZE_MAX/sizeof(T)`, which on 64-bit
 * platforms is trivially false (the check still fires on 32-bit where
 * it can actually overflow). */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wunused-function"
#  pragma GCC diagnostic ignored "-Wtype-limits"
#endif

/* ======================================================================
 * Output buffer helpers
 * ====================================================================== */

void ww_buf_init(ww_buf_t *b) {
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

void ww_buf_free(ww_buf_t *b) {
    free(b->data);
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

int ww_buf_reserve(ww_buf_t *b, size_t additional) {
    size_t need;
    if (additional > SIZE_MAX - b->len) return WW_ERR_OVERFLOW;
    need = b->len + additional;
    if (need > b->cap) {
        size_t new_cap = b->cap ? b->cap : 64;
        while (new_cap < need) {
            if (new_cap > SIZE_MAX / 2) return WW_ERR_OVERFLOW;
            new_cap *= 2;
        }
        uint8_t *nd = (uint8_t *)realloc(b->data, new_cap);
        if (!nd) return WW_ERR_NOMEM;
        b->data = nd;
        b->cap = new_cap;
    }
    return WW_OK;
}

/* ======================================================================
 * Writer helpers
 * ====================================================================== */

static int w_bytes(ww_buf_t *b, const void *src, size_t n) {
    int rc = ww_buf_reserve(b, n);
    if (rc) return rc;
    if (n > b->cap - b->len) return WW_ERR_OVERFLOW;
    memcpy(b->data + b->len, src, n);
    b->len += n;
    return WW_OK;
}

static int w_u32(ww_buf_t *b, uint32_t v) {
    uint8_t out[4];
    out[0] = (uint8_t)(v);
    out[1] = (uint8_t)(v >> 8);
    out[2] = (uint8_t)(v >> 16);
    out[3] = (uint8_t)(v >> 24);
    return w_bytes(b, out, 4);
}
static int w_bool(ww_buf_t *b, bool v) { return w_u32(b, v ? 1u : 0u); }
static int w_i32(ww_buf_t *b, int32_t v) { return w_u32(b, (uint32_t)v); }

static int w_u64(ww_buf_t *b, uint64_t v) {
    uint8_t out[8];
    out[0] = (uint8_t)(v);
    out[1] = (uint8_t)(v >> 8);
    out[2] = (uint8_t)(v >> 16);
    out[3] = (uint8_t)(v >> 24);
    out[4] = (uint8_t)(v >> 32);
    out[5] = (uint8_t)(v >> 40);
    out[6] = (uint8_t)(v >> 48);
    out[7] = (uint8_t)(v >> 56);
    return w_bytes(b, out, 8);
}
static int w_i64(ww_buf_t *b, int64_t v) { return w_u64(b, (uint64_t)v); }

static int w_f32(ww_buf_t *b, float v) {
    uint32_t bits;
    memcpy(&bits, &v, 4);
    return w_u32(b, bits);
}
static int w_f64(ww_buf_t *b, double v) {
    uint64_t bits;
    memcpy(&bits, &v, 8);
    return w_u64(b, bits);
}

static int w_pad4(ww_buf_t *b) {
    static const uint8_t zeros[3] = {0, 0, 0};
    size_t pad = (4 - (b->len & 3)) & 3;
    if (pad == 0) return WW_OK;
    return w_bytes(b, zeros, pad);
}

static int w_string(ww_buf_t *b, const char *s) {
    size_t n = s ? strlen(s) : 0;
    if (n > 0xfffffffeULL) return WW_ERR_OVERFLOW;
    uint32_t len = (uint32_t)(n + 1);  /* includes NUL */
    int rc = w_u32(b, len);
    if (rc) return rc;
    rc = w_bytes(b, s ? s : "", n);
    if (rc) return rc;
    static const uint8_t nul = 0;
    rc = w_bytes(b, &nul, 1);
    if (rc) return rc;
    return w_pad4(b);
}

static int w_rect(ww_buf_t *b, const ww_rect_t *r) {
    int rc;
    if ((rc = w_f32(b, r->x))) return rc;
    if ((rc = w_f32(b, r->y))) return rc;
    if ((rc = w_f32(b, r->w))) return rc;
    if ((rc = w_f32(b, r->h))) return rc;
    return WW_OK;
}

static int w_array_u32(ww_buf_t *b, const ww_array_u32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_u32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_i32(ww_buf_t *b, const ww_array_i32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_i32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_u64(ww_buf_t *b, const ww_array_u64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_u64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_i64(ww_buf_t *b, const ww_array_i64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_i64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_f32(ww_buf_t *b, const ww_array_f32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_f32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_f64(ww_buf_t *b, const ww_array_f64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_f64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_string(ww_buf_t *b, const ww_array_string_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_string(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_kv_list(ww_buf_t *b, const ww_kv_list_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_string(b, a->data[i].key);
        if (rc) return rc;
        rc = w_string(b, a->data[i].value);
        if (rc) return rc;
    }
    return WW_OK;
}

/* ======================================================================
 * Reader helpers
 * ====================================================================== */

typedef struct {
    const uint8_t *buf;
    size_t pos;
    size_t len;
} ww_rd_t;

static int rd_need(const ww_rd_t *r, size_t n) {
    return (r->len - r->pos >= n) ? WW_OK : WW_ERR_SHORT;
}

static int rd_u32(ww_rd_t *r, uint32_t *out) {
    int rc = rd_need(r, 4);
    if (rc) return rc;
    const uint8_t *p = r->buf + r->pos;
    *out = (uint32_t)p[0] | ((uint32_t)p[1] << 8)
        | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
    r->pos += 4;
    return WW_OK;
}
static int rd_bool(ww_rd_t *r, bool *out) {
    uint32_t v;
    int rc = rd_u32(r, &v);
    if (rc) return rc;
    if (v > 1u) return WW_ERR_BAD_BOOL;
    *out = v != 0u;
    return WW_OK;
}
static int rd_i32(ww_rd_t *r, int32_t *out) {
    uint32_t v; int rc = rd_u32(r, &v); if (rc) return rc; *out = (int32_t)v; return WW_OK;
}
static int rd_u64(ww_rd_t *r, uint64_t *out) {
    int rc = rd_need(r, 8);
    if (rc) return rc;
    const uint8_t *p = r->buf + r->pos;
    *out = (uint64_t)p[0] | ((uint64_t)p[1] << 8)
        | ((uint64_t)p[2] << 16) | ((uint64_t)p[3] << 24)
        | ((uint64_t)p[4] << 32) | ((uint64_t)p[5] << 40)
        | ((uint64_t)p[6] << 48) | ((uint64_t)p[7] << 56);
    r->pos += 8;
    return WW_OK;
}
static int rd_i64(ww_rd_t *r, int64_t *out) {
    uint64_t v; int rc = rd_u64(r, &v); if (rc) return rc; *out = (int64_t)v; return WW_OK;
}
static int rd_f32(ww_rd_t *r, float *out) {
    uint32_t bits; int rc = rd_u32(r, &bits); if (rc) return rc;
    memcpy(out, &bits, 4);
    return WW_OK;
}
static int rd_f64(ww_rd_t *r, double *out) {
    uint64_t bits; int rc = rd_u64(r, &bits); if (rc) return rc;
    memcpy(out, &bits, 8);
    return WW_OK;
}

static int rd_rect(ww_rd_t *r, ww_rect_t *out) {
    int rc;
    if ((rc = rd_f32(r, &out->x))) return rc;
    if ((rc = rd_f32(r, &out->y))) return rc;
    if ((rc = rd_f32(r, &out->w))) return rc;
    if ((rc = rd_f32(r, &out->h))) return rc;
    return WW_OK;
}

static int rd_string(ww_rd_t *r, char **out) {
    uint32_t len;
    int rc = rd_u32(r, &len);
    if (rc) return rc;
    if (len == 0) return WW_ERR_BAD_STRING;  /* includes NUL */
    size_t padded = ((size_t)len + 3u) & ~(size_t)3u;
    if (padded < (size_t)len) return WW_ERR_OVERFLOW;
    rc = rd_need(r, padded);
    if (rc) return rc;
    if (r->buf[r->pos + len - 1] != 0) return WW_ERR_BAD_STRING;
    char *s = (char *)malloc(len);
    if (!s) return WW_ERR_NOMEM;
    memcpy(s, r->buf + r->pos, len);
    *out = s;
    r->pos += padded;
    return WW_OK;
}

/* Guard against an untrusted count forcing a huge allocation (DoS). */
#define DEFINE_ARRAY_READER(NAME, CTYPE, READ_ONE)                     \
    static int rd_array_##NAME(ww_rd_t *r, ww_array_##NAME##_t *out) { \
        uint32_t n;                                                    \
        int rc = rd_u32(r, &n);                                        \
        if (rc) return rc;                                             \
        out->count = 0;                                                \
        out->data = NULL;                                              \
        if (n == 0) return WW_OK;                                      \
        if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;      \
        if ((size_t)n > (SIZE_MAX / sizeof(CTYPE))) return WW_ERR_BAD_ARRAY; \
        CTYPE *arr = (CTYPE *)malloc((size_t)n * sizeof(CTYPE));       \
        if (!arr) return WW_ERR_NOMEM;                                 \
        for (uint32_t i = 0; i < n; i++) {                             \
            rc = READ_ONE(r, &arr[i]);                                 \
            if (rc) { free(arr); return rc; }                          \
        }                                                              \
        out->count = n;                                                \
        out->data = arr;                                               \
        return WW_OK;                                                  \
    }

DEFINE_ARRAY_READER(u32, uint32_t, rd_u32)
DEFINE_ARRAY_READER(i32, int32_t,  rd_i32)
DEFINE_ARRAY_READER(u64, uint64_t, rd_u64)
DEFINE_ARRAY_READER(i64, int64_t,  rd_i64)
DEFINE_ARRAY_READER(f32, float,    rd_f32)
DEFINE_ARRAY_READER(f64, double,   rd_f64)

static int rd_array_string(ww_rd_t *r, ww_array_string_t *out) {
    uint32_t n;
    int rc = rd_u32(r, &n);
    if (rc) return rc;
    out->count = 0;
    out->data = NULL;
    if (n == 0) return WW_OK;
    if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;
    if ((size_t)n > (SIZE_MAX / sizeof(char *))) return WW_ERR_BAD_ARRAY;
    char **arr = (char **)calloc(n, sizeof(char *));
    if (!arr) return WW_ERR_NOMEM;
    for (uint32_t i = 0; i < n; i++) {
        rc = rd_string(r, &arr[i]);
        if (rc) {
            for (uint32_t j = 0; j < i; j++) free(arr[j]);
            free(arr);
            return rc;
        }
    }
    out->count = n;
    out->data = arr;
    return WW_OK;
}

static int rd_kv_list(ww_rd_t *r, ww_kv_list_t *out) {
    uint32_t n;
    int rc = rd_u32(r, &n);
    if (rc) return rc;
    out->count = 0;
    out->data = NULL;
    if (n == 0) return WW_OK;
    if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;
    if ((size_t)n > (SIZE_MAX / sizeof(ww_kv_t))) return WW_ERR_BAD_ARRAY;
    ww_kv_t *arr = (ww_kv_t *)calloc(n, sizeof(ww_kv_t));
    if (!arr) return WW_ERR_NOMEM;
    for (uint32_t i = 0; i < n; i++) {
        rc = rd_string(r, &arr[i].key);
        if (!rc) rc = rd_string(r, &arr[i].value);
        if (rc) {
            for (uint32_t j = 0; j <= i; j++) {
                free(arr[j].key);
                free(arr[j].value);
            }
            free(arr);
            return rc;
        }
    }
    out->count = n;
    out->data = arr;
    return WW_OK;
}

static void free_array_string(ww_array_string_t *a) {
    if (!a->data) { a->count = 0; return; }
    for (uint32_t i = 0; i < a->count; i++) free(a->data[i]);
    free(a->data);
    a->data = NULL;
    a->count = 0;
}
static void free_kv_list(ww_kv_list_t *a) {
    if (!a->data) { a->count = 0; return; }
    for (uint32_t i = 0; i < a->count; i++) {
        free(a->data[i].key);
        free(a->data[i].value);
    }
    free(a->data);
    a->data = NULL;
    a->count = 0;
}

#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic pop
#endif

/* ======================================================================
 * Per-message implementations
 * ====================================================================== */

static int w_pointer_button_state(ww_buf_t *b, waywallen_pointer_button_state_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_pointer_button_state(ww_rd_t *r, waywallen_pointer_button_state_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_POINTER_BUTTON_STATE_RELEASED; return WW_OK;
    case 1: *out = WAYWALLEN_POINTER_BUTTON_STATE_PRESSED; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_pointer_axis_source(ww_buf_t *b, waywallen_pointer_axis_source_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_pointer_axis_source(ww_rd_t *r, waywallen_pointer_axis_source_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_POINTER_AXIS_SOURCE_WHEEL; return WW_OK;
    case 1: *out = WAYWALLEN_POINTER_AXIS_SOURCE_FINGER; return WW_OK;
    case 2: *out = WAYWALLEN_POINTER_AXIS_SOURCE_CONTINUOUS; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_media_playback_state(ww_buf_t *b, waywallen_media_playback_state_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_media_playback_state(ww_rd_t *r, waywallen_media_playback_state_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_MEDIA_PLAYBACK_STATE_STOPPED; return WW_OK;
    case 1: *out = WAYWALLEN_MEDIA_PLAYBACK_STATE_PLAYING; return WW_OK;
    case 2: *out = WAYWALLEN_MEDIA_PLAYBACK_STATE_PAUSED; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_log_level(ww_buf_t *b, waywallen_log_level_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_log_level(ww_rd_t *r, waywallen_log_level_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_LOG_LEVEL_OFF; return WW_OK;
    case 1: *out = WAYWALLEN_LOG_LEVEL_ERROR; return WW_OK;
    case 2: *out = WAYWALLEN_LOG_LEVEL_WARN; return WW_OK;
    case 3: *out = WAYWALLEN_LOG_LEVEL_INFO; return WW_OK;
    case 4: *out = WAYWALLEN_LOG_LEVEL_DEBUG; return WW_OK;
    case 5: *out = WAYWALLEN_LOG_LEVEL_TRACE; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_event_subscription_status(ww_buf_t *b, waywallen_event_subscription_status_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_event_subscription_status(ww_rd_t *r, waywallen_event_subscription_status_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_APPLIED; return WW_OK;
    case 1: *out = WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_INVALID; return WW_OK;
    case 2: *out = WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_STALE_REVISION; return WW_OK;
    case 3: *out = WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_REVISION_CONFLICT; return WW_OK;
    case 4: *out = WAYWALLEN_EVENT_SUBSCRIPTION_STATUS_LIMIT_EXCEEDED; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_buffer_path(ww_buf_t *b, waywallen_buffer_path_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_buffer_path(ww_rd_t *r, waywallen_buffer_path_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_BUFFER_PATH_OPTIMIZED_SAME_DEVICE; return WW_OK;
    case 1: *out = WAYWALLEN_BUFFER_PATH_OPTIMIZED_SAME_VENDOR; return WW_OK;
    case 2: *out = WAYWALLEN_BUFFER_PATH_COMPAT_LINEAR; return WW_OK;
    case 3: *out = WAYWALLEN_BUFFER_PATH_COMPAT_CPU_READBACK; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_buffer_memory_source(ww_buf_t *b, waywallen_buffer_memory_source_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_buffer_memory_source(ww_rd_t *r, waywallen_buffer_memory_source_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_BUFFER_MEMORY_SOURCE_GPU_NATIVE; return WW_OK;
    case 1: *out = WAYWALLEN_BUFFER_MEMORY_SOURCE_GPU_LINEAR; return WW_OK;
    case 2: *out = WAYWALLEN_BUFFER_MEMORY_SOURCE_DMABUF_HEAP; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_buffer_allocation_failure_kind(ww_buf_t *b, waywallen_buffer_allocation_failure_kind_t v) {
    return w_u32(b, (uint32_t)v);
}

static int rd_buffer_allocation_failure_kind(ww_rd_t *r, waywallen_buffer_allocation_failure_kind_t *out) {
    uint32_t value;
    int rc = rd_u32(r, &value);
    if (rc) return rc;
    switch (value) {
    case 0: *out = WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_ALLOCATOR_REJECTED; return WW_OK;
    case 1: *out = WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_RESOURCE_EXHAUSTED; return WW_OK;
    case 2: *out = WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_UNSUPPORTED; return WW_OK;
    case 3: *out = WAYWALLEN_BUFFER_ALLOCATION_FAILURE_KIND_OTHER; return WW_OK;
    default: return WW_ERR_BAD_ENUM;
    }
}

static int w_audio_stream_format(ww_buf_t *b, const waywallen_audio_stream_format_t *v) {
    int rc;
    if ((rc = w_u32(b, v->sample_rate_hz))) return rc;
    if ((rc = w_u32(b, v->channels))) return rc;
    return WW_OK;
}

static int rd_audio_stream_format(ww_rd_t *r, waywallen_audio_stream_format_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->sample_rate_hz))) return rc;
    if ((rc = rd_u32(r, &v->channels))) return rc;
    return WW_OK;
}

static void free_audio_stream_format(waywallen_audio_stream_format_t *v) {
    (void)v;
}

void waywallen_audio_stream_format_free(waywallen_audio_stream_format_t *value) {
    if (!value) return;
    free_audio_stream_format(value);
    memset(value, 0, sizeof(*value));
}

static int w_audio_window(ww_buf_t *b, const waywallen_audio_window_t *v) {
    int rc;
    if ((rc = w_u64(b, v->subscription_revision))) return rc;
    if ((rc = w_u64(b, v->generation))) return rc;
    if ((rc = w_u64(b, v->sequence))) return rc;
    if ((rc = w_u64(b, v->captured_at_ns))) return rc;
    if ((rc = w_u64(b, v->end_sample_frame))) return rc;
    if ((rc = w_audio_stream_format(b, &v->format))) return rc;
    if ((rc = w_u32(b, v->frames))) return rc;
    if ((rc = w_u32(b, v->flags))) return rc;
    if ((rc = w_array_f32(b, &v->samples))) return rc;
    return WW_OK;
}

static int rd_audio_window(ww_rd_t *r, waywallen_audio_window_t *v) {
    int rc;
    if ((rc = rd_u64(r, &v->subscription_revision))) return rc;
    if ((rc = rd_u64(r, &v->generation))) return rc;
    if ((rc = rd_u64(r, &v->sequence))) return rc;
    if ((rc = rd_u64(r, &v->captured_at_ns))) return rc;
    if ((rc = rd_u64(r, &v->end_sample_frame))) return rc;
    if ((rc = rd_audio_stream_format(r, &v->format))) return rc;
    if ((rc = rd_u32(r, &v->frames))) return rc;
    if ((rc = rd_u32(r, &v->flags))) return rc;
    if ((rc = rd_array_f32(r, &v->samples))) return rc;
    return WW_OK;
}

static void free_audio_window(waywallen_audio_window_t *v) {
    free_audio_stream_format(&v->format);
    free(v->samples.data); v->samples.data = NULL; v->samples.count = 0;
}

void waywallen_audio_window_free(waywallen_audio_window_t *value) {
    if (!value) return;
    free_audio_window(value);
    memset(value, 0, sizeof(*value));
}

static int w_buffer_format(ww_buf_t *b, const waywallen_buffer_format_t *v) {
    int rc;
    if ((rc = w_u32(b, v->fourcc))) return rc;
    if ((rc = w_u64(b, v->modifier))) return rc;
    if ((rc = w_u32(b, v->plane_count))) return rc;
    return WW_OK;
}

static int rd_buffer_format(ww_rd_t *r, waywallen_buffer_format_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->fourcc))) return rc;
    if ((rc = rd_u64(r, &v->modifier))) return rc;
    if ((rc = rd_u32(r, &v->plane_count))) return rc;
    return WW_OK;
}

static void free_buffer_format(waywallen_buffer_format_t *v) {
    (void)v;
}

void waywallen_buffer_format_free(waywallen_buffer_format_t *value) {
    if (!value) return;
    free_buffer_format(value);
    memset(value, 0, sizeof(*value));
}

static int w_bind_failure(ww_buf_t *b, const waywallen_bind_failure_t *v) {
    int rc;
    if ((rc = w_buffer_format(b, &v->format))) return rc;
    if ((rc = w_buffer_allocation_failure_kind(b, v->kind))) return rc;
    if ((rc = w_string(b, v->message))) return rc;
    return WW_OK;
}

static int rd_bind_failure(ww_rd_t *r, waywallen_bind_failure_t *v) {
    int rc;
    if ((rc = rd_buffer_format(r, &v->format))) return rc;
    if ((rc = rd_buffer_allocation_failure_kind(r, &v->kind))) return rc;
    if ((rc = rd_string(r, &v->message))) return rc;
    return WW_OK;
}

static void free_bind_failure(waywallen_bind_failure_t *v) {
    free_buffer_format(&v->format);
    free(v->message); v->message = NULL;
}

void waywallen_bind_failure_free(waywallen_bind_failure_t *value) {
    if (!value) return;
    free_bind_failure(value);
    memset(value, 0, sizeof(*value));
}

static int w_buffer_directive(ww_buf_t *b, const waywallen_buffer_directive_t *v) {
    int rc;
    if ((rc = w_buffer_format(b, &v->format))) return rc;
    if ((rc = w_u32(b, v->sync_mode))) return rc;
    if ((rc = w_u32(b, v->color))) return rc;
    if ((rc = w_u32(b, v->mem_hint))) return rc;
    if ((rc = w_u32(b, v->count))) return rc;
    if ((rc = w_buffer_path(b, v->path))) return rc;
    if ((rc = w_buffer_memory_source(b, v->memory_source))) return rc;
    return WW_OK;
}

static int rd_buffer_directive(ww_rd_t *r, waywallen_buffer_directive_t *v) {
    int rc;
    if ((rc = rd_buffer_format(r, &v->format))) return rc;
    if ((rc = rd_u32(r, &v->sync_mode))) return rc;
    if ((rc = rd_u32(r, &v->color))) return rc;
    if ((rc = rd_u32(r, &v->mem_hint))) return rc;
    if ((rc = rd_u32(r, &v->count))) return rc;
    if ((rc = rd_buffer_path(r, &v->path))) return rc;
    if ((rc = rd_buffer_memory_source(r, &v->memory_source))) return rc;
    return WW_OK;
}

static void free_buffer_directive(waywallen_buffer_directive_t *v) {
    free_buffer_format(&v->format);
}

void waywallen_buffer_directive_free(waywallen_buffer_directive_t *value) {
    if (!value) return;
    free_buffer_directive(value);
    memset(value, 0, sizeof(*value));
}

static int w_extent(ww_buf_t *b, const waywallen_extent_t *v) {
    int rc;
    if ((rc = w_u32(b, v->width))) return rc;
    if ((rc = w_u32(b, v->height))) return rc;
    return WW_OK;
}

static int rd_extent(ww_rd_t *r, waywallen_extent_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->width))) return rc;
    if ((rc = rd_u32(r, &v->height))) return rc;
    return WW_OK;
}

static void free_extent(waywallen_extent_t *v) {
    (void)v;
}

void waywallen_extent_free(waywallen_extent_t *value) {
    if (!value) return;
    free_extent(value);
    memset(value, 0, sizeof(*value));
}

static int w_buffer_pool(ww_buf_t *b, const waywallen_buffer_pool_t *v) {
    int rc;
    if ((rc = w_u64(b, v->generation))) return rc;
    if ((rc = w_u32(b, v->flags))) return rc;
    if ((rc = w_u32(b, v->count))) return rc;
    if ((rc = w_buffer_format(b, &v->format))) return rc;
    if ((rc = w_extent(b, &v->extent))) return rc;
    if ((rc = w_array_u32(b, &v->stride))) return rc;
    if ((rc = w_array_u32(b, &v->plane_offset))) return rc;
    if ((rc = w_array_u64(b, &v->size))) return rc;
    return WW_OK;
}

static int rd_buffer_pool(ww_rd_t *r, waywallen_buffer_pool_t *v) {
    int rc;
    if ((rc = rd_u64(r, &v->generation))) return rc;
    if ((rc = rd_u32(r, &v->flags))) return rc;
    if ((rc = rd_u32(r, &v->count))) return rc;
    if ((rc = rd_buffer_format(r, &v->format))) return rc;
    if ((rc = rd_extent(r, &v->extent))) return rc;
    if ((rc = rd_array_u32(r, &v->stride))) return rc;
    if ((rc = rd_array_u32(r, &v->plane_offset))) return rc;
    if ((rc = rd_array_u64(r, &v->size))) return rc;
    return WW_OK;
}

static void free_buffer_pool(waywallen_buffer_pool_t *v) {
    free_buffer_format(&v->format);
    free_extent(&v->extent);
    free(v->stride.data); v->stride.data = NULL; v->stride.count = 0;
    free(v->plane_offset.data); v->plane_offset.data = NULL; v->plane_offset.count = 0;
    free(v->size.data); v->size.data = NULL; v->size.count = 0;
}

void waywallen_buffer_pool_free(waywallen_buffer_pool_t *value) {
    if (!value) return;
    free_buffer_pool(value);
    memset(value, 0, sizeof(*value));
}

static int w_control_transition(ww_buf_t *b, const waywallen_control_transition_t *v) {
    int rc;
    if ((rc = w_u32(b, v->fade_ms))) return rc;
    return WW_OK;
}

static int rd_control_transition(ww_rd_t *r, waywallen_control_transition_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->fade_ms))) return rc;
    return WW_OK;
}

static void free_control_transition(waywallen_control_transition_t *v) {
    (void)v;
}

void waywallen_control_transition_free(waywallen_control_transition_t *value) {
    if (!value) return;
    free_control_transition(value);
    memset(value, 0, sizeof(*value));
}

static int w_drm_node(ww_buf_t *b, const waywallen_drm_node_t *v) {
    int rc;
    if ((rc = w_u32(b, v->major))) return rc;
    if ((rc = w_u32(b, v->minor))) return rc;
    return WW_OK;
}

static int rd_drm_node(ww_rd_t *r, waywallen_drm_node_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->major))) return rc;
    if ((rc = rd_u32(r, &v->minor))) return rc;
    return WW_OK;
}

static void free_drm_node(waywallen_drm_node_t *v) {
    (void)v;
}

void waywallen_drm_node_free(waywallen_drm_node_t *value) {
    if (!value) return;
    free_drm_node(value);
    memset(value, 0, sizeof(*value));
}

static int w_event_subscription(ww_buf_t *b, const waywallen_event_subscription_t *v) {
    int rc;
    if ((rc = w_u64(b, v->revision))) return rc;
    if ((rc = w_array_string(b, &v->kinds))) return rc;
    return WW_OK;
}

static int rd_event_subscription(ww_rd_t *r, waywallen_event_subscription_t *v) {
    int rc;
    if ((rc = rd_u64(r, &v->revision))) return rc;
    if ((rc = rd_array_string(r, &v->kinds))) return rc;
    return WW_OK;
}

static void free_event_subscription(waywallen_event_subscription_t *v) {
    free_array_string(&v->kinds);
}

void waywallen_event_subscription_free(waywallen_event_subscription_t *value) {
    if (!value) return;
    free_event_subscription(value);
    memset(value, 0, sizeof(*value));
}

static int w_event_subscription_result(ww_buf_t *b, const waywallen_event_subscription_result_t *v) {
    int rc;
    if ((rc = w_u64(b, v->revision))) return rc;
    if ((rc = w_event_subscription_status(b, v->status))) return rc;
    if ((rc = w_array_string(b, &v->kinds))) return rc;
    if ((rc = w_string(b, v->reason))) return rc;
    return WW_OK;
}

static int rd_event_subscription_result(ww_rd_t *r, waywallen_event_subscription_result_t *v) {
    int rc;
    if ((rc = rd_u64(r, &v->revision))) return rc;
    if ((rc = rd_event_subscription_status(r, &v->status))) return rc;
    if ((rc = rd_array_string(r, &v->kinds))) return rc;
    if ((rc = rd_string(r, &v->reason))) return rc;
    return WW_OK;
}

static void free_event_subscription_result(waywallen_event_subscription_result_t *v) {
    free_array_string(&v->kinds);
    free(v->reason); v->reason = NULL;
}

void waywallen_event_subscription_result_free(waywallen_event_subscription_result_t *value) {
    if (!value) return;
    free_event_subscription_result(value);
    memset(value, 0, sizeof(*value));
}

static int w_frame(ww_buf_t *b, const waywallen_frame_t *v) {
    int rc;
    if ((rc = w_u32(b, v->image_index))) return rc;
    if ((rc = w_u64(b, v->sequence))) return rc;
    if ((rc = w_u64(b, v->produced_at_ns))) return rc;
    if ((rc = w_u64(b, v->release_point))) return rc;
    return WW_OK;
}

static int rd_frame(ww_rd_t *r, waywallen_frame_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->image_index))) return rc;
    if ((rc = rd_u64(r, &v->sequence))) return rc;
    if ((rc = rd_u64(r, &v->produced_at_ns))) return rc;
    if ((rc = rd_u64(r, &v->release_point))) return rc;
    return WW_OK;
}

static void free_frame(waywallen_frame_t *v) {
    (void)v;
}

void waywallen_frame_free(waywallen_frame_t *value) {
    if (!value) return;
    free_frame(value);
    memset(value, 0, sizeof(*value));
}

static int w_init_rejection(ww_buf_t *b, const waywallen_init_rejection_t *v) {
    int rc;
    if ((rc = w_u32(b, v->received_protocol_version))) return rc;
    if ((rc = w_u32(b, v->supported_protocol_version))) return rc;
    if ((rc = w_u32(b, v->received_spawn_version))) return rc;
    if ((rc = w_u32(b, v->supported_spawn_version))) return rc;
    if ((rc = w_string(b, v->reason))) return rc;
    return WW_OK;
}

static int rd_init_rejection(ww_rd_t *r, waywallen_init_rejection_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->received_protocol_version))) return rc;
    if ((rc = rd_u32(r, &v->supported_protocol_version))) return rc;
    if ((rc = rd_u32(r, &v->received_spawn_version))) return rc;
    if ((rc = rd_u32(r, &v->supported_spawn_version))) return rc;
    if ((rc = rd_string(r, &v->reason))) return rc;
    return WW_OK;
}

static void free_init_rejection(waywallen_init_rejection_t *v) {
    free(v->reason); v->reason = NULL;
}

void waywallen_init_rejection_free(waywallen_init_rejection_t *value) {
    if (!value) return;
    free_init_rejection(value);
    memset(value, 0, sizeof(*value));
}

static int w_mpris_snapshot(ww_buf_t *b, const waywallen_mpris_snapshot_t *v) {
    int rc;
    if ((rc = w_media_playback_state(b, v->state))) return rc;
    if ((rc = w_string(b, v->title))) return rc;
    if ((rc = w_string(b, v->artist))) return rc;
    if ((rc = w_string(b, v->album))) return rc;
    if ((rc = w_string(b, v->album_artist))) return rc;
    if ((rc = w_string(b, v->art_url))) return rc;
    if ((rc = w_string(b, v->previous_art_url))) return rc;
    return WW_OK;
}

static int rd_mpris_snapshot(ww_rd_t *r, waywallen_mpris_snapshot_t *v) {
    int rc;
    if ((rc = rd_media_playback_state(r, &v->state))) return rc;
    if ((rc = rd_string(r, &v->title))) return rc;
    if ((rc = rd_string(r, &v->artist))) return rc;
    if ((rc = rd_string(r, &v->album))) return rc;
    if ((rc = rd_string(r, &v->album_artist))) return rc;
    if ((rc = rd_string(r, &v->art_url))) return rc;
    if ((rc = rd_string(r, &v->previous_art_url))) return rc;
    return WW_OK;
}

static void free_mpris_snapshot(waywallen_mpris_snapshot_t *v) {
    free(v->title); v->title = NULL;
    free(v->artist); v->artist = NULL;
    free(v->album); v->album = NULL;
    free(v->album_artist); v->album_artist = NULL;
    free(v->art_url); v->art_url = NULL;
    free(v->previous_art_url); v->previous_art_url = NULL;
}

void waywallen_mpris_snapshot_free(waywallen_mpris_snapshot_t *value) {
    if (!value) return;
    free_mpris_snapshot(value);
    memset(value, 0, sizeof(*value));
}

static int w_pointer_axis(ww_buf_t *b, const waywallen_pointer_axis_t *v) {
    int rc;
    if ((rc = w_f32(b, v->x))) return rc;
    if ((rc = w_f32(b, v->y))) return rc;
    if ((rc = w_f32(b, v->delta_x))) return rc;
    if ((rc = w_f32(b, v->delta_y))) return rc;
    if ((rc = w_pointer_axis_source(b, v->source))) return rc;
    if ((rc = w_u64(b, v->timestamp_us))) return rc;
    if ((rc = w_u32(b, v->modifiers))) return rc;
    return WW_OK;
}

static int rd_pointer_axis(ww_rd_t *r, waywallen_pointer_axis_t *v) {
    int rc;
    if ((rc = rd_f32(r, &v->x))) return rc;
    if ((rc = rd_f32(r, &v->y))) return rc;
    if ((rc = rd_f32(r, &v->delta_x))) return rc;
    if ((rc = rd_f32(r, &v->delta_y))) return rc;
    if ((rc = rd_pointer_axis_source(r, &v->source))) return rc;
    if ((rc = rd_u64(r, &v->timestamp_us))) return rc;
    if ((rc = rd_u32(r, &v->modifiers))) return rc;
    return WW_OK;
}

static void free_pointer_axis(waywallen_pointer_axis_t *v) {
    (void)v;
}

void waywallen_pointer_axis_free(waywallen_pointer_axis_t *value) {
    if (!value) return;
    free_pointer_axis(value);
    memset(value, 0, sizeof(*value));
}

static int w_pointer_button(ww_buf_t *b, const waywallen_pointer_button_t *v) {
    int rc;
    if ((rc = w_f32(b, v->x))) return rc;
    if ((rc = w_f32(b, v->y))) return rc;
    if ((rc = w_u32(b, v->button))) return rc;
    if ((rc = w_pointer_button_state(b, v->state))) return rc;
    if ((rc = w_u64(b, v->timestamp_us))) return rc;
    if ((rc = w_u32(b, v->modifiers))) return rc;
    return WW_OK;
}

static int rd_pointer_button(ww_rd_t *r, waywallen_pointer_button_t *v) {
    int rc;
    if ((rc = rd_f32(r, &v->x))) return rc;
    if ((rc = rd_f32(r, &v->y))) return rc;
    if ((rc = rd_u32(r, &v->button))) return rc;
    if ((rc = rd_pointer_button_state(r, &v->state))) return rc;
    if ((rc = rd_u64(r, &v->timestamp_us))) return rc;
    if ((rc = rd_u32(r, &v->modifiers))) return rc;
    return WW_OK;
}

static void free_pointer_button(waywallen_pointer_button_t *v) {
    (void)v;
}

void waywallen_pointer_button_free(waywallen_pointer_button_t *value) {
    if (!value) return;
    free_pointer_button(value);
    memset(value, 0, sizeof(*value));
}

static int w_pointer_motion(ww_buf_t *b, const waywallen_pointer_motion_t *v) {
    int rc;
    if ((rc = w_f32(b, v->x))) return rc;
    if ((rc = w_f32(b, v->y))) return rc;
    if ((rc = w_u64(b, v->timestamp_us))) return rc;
    if ((rc = w_u32(b, v->modifiers))) return rc;
    return WW_OK;
}

static int rd_pointer_motion(ww_rd_t *r, waywallen_pointer_motion_t *v) {
    int rc;
    if ((rc = rd_f32(r, &v->x))) return rc;
    if ((rc = rd_f32(r, &v->y))) return rc;
    if ((rc = rd_u64(r, &v->timestamp_us))) return rc;
    if ((rc = rd_u32(r, &v->modifiers))) return rc;
    return WW_OK;
}

static void free_pointer_motion(waywallen_pointer_motion_t *v) {
    (void)v;
}

void waywallen_pointer_motion_free(waywallen_pointer_motion_t *value) {
    if (!value) return;
    free_pointer_motion(value);
    memset(value, 0, sizeof(*value));
}

static int w_producer_capabilities(ww_buf_t *b, const waywallen_producer_capabilities_t *v) {
    int rc;
    if ((rc = w_array_u32(b, &v->fourccs))) return rc;
    if ((rc = w_array_u32(b, &v->mod_counts))) return rc;
    if ((rc = w_array_u64(b, &v->modifiers))) return rc;
    if ((rc = w_array_u32(b, &v->plane_counts))) return rc;
    if ((rc = w_array_u32(b, &v->device_uuid))) return rc;
    if ((rc = w_array_u32(b, &v->driver_uuid))) return rc;
    if ((rc = w_drm_node(b, &v->drm_node))) return rc;
    if ((rc = w_u32(b, v->mem_hints))) return rc;
    if ((rc = w_u32(b, v->sync_caps))) return rc;
    if ((rc = w_u32(b, v->color_caps))) return rc;
    if ((rc = w_extent(b, &v->max_extent))) return rc;
    return WW_OK;
}

static int rd_producer_capabilities(ww_rd_t *r, waywallen_producer_capabilities_t *v) {
    int rc;
    if ((rc = rd_array_u32(r, &v->fourccs))) return rc;
    if ((rc = rd_array_u32(r, &v->mod_counts))) return rc;
    if ((rc = rd_array_u64(r, &v->modifiers))) return rc;
    if ((rc = rd_array_u32(r, &v->plane_counts))) return rc;
    if ((rc = rd_array_u32(r, &v->device_uuid))) return rc;
    if ((rc = rd_array_u32(r, &v->driver_uuid))) return rc;
    if ((rc = rd_drm_node(r, &v->drm_node))) return rc;
    if ((rc = rd_u32(r, &v->mem_hints))) return rc;
    if ((rc = rd_u32(r, &v->sync_caps))) return rc;
    if ((rc = rd_u32(r, &v->color_caps))) return rc;
    if ((rc = rd_extent(r, &v->max_extent))) return rc;
    return WW_OK;
}

static void free_producer_capabilities(waywallen_producer_capabilities_t *v) {
    free(v->fourccs.data); v->fourccs.data = NULL; v->fourccs.count = 0;
    free(v->mod_counts.data); v->mod_counts.data = NULL; v->mod_counts.count = 0;
    free(v->modifiers.data); v->modifiers.data = NULL; v->modifiers.count = 0;
    free(v->plane_counts.data); v->plane_counts.data = NULL; v->plane_counts.count = 0;
    free(v->device_uuid.data); v->device_uuid.data = NULL; v->device_uuid.count = 0;
    free(v->driver_uuid.data); v->driver_uuid.data = NULL; v->driver_uuid.count = 0;
    free_drm_node(&v->drm_node);
    free_extent(&v->max_extent);
}

void waywallen_producer_capabilities_free(waywallen_producer_capabilities_t *value) {
    if (!value) return;
    free_producer_capabilities(value);
    memset(value, 0, sizeof(*value));
}

static int w_renderer_init(ww_buf_t *b, const waywallen_renderer_init_t *v) {
    int rc;
    if ((rc = w_u32(b, v->protocol_version))) return rc;
    if ((rc = w_u32(b, v->spawn_version))) return rc;
    if ((rc = w_kv_list(b, &v->settings))) return rc;
    if ((rc = w_string(b, v->user_properties))) return rc;
    if ((rc = w_u32(b, v->display_width))) return rc;
    if ((rc = w_u32(b, v->display_height))) return rc;
    return WW_OK;
}

static int rd_renderer_init(ww_rd_t *r, waywallen_renderer_init_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->protocol_version))) return rc;
    if ((rc = rd_u32(r, &v->spawn_version))) return rc;
    if ((rc = rd_kv_list(r, &v->settings))) return rc;
    if ((rc = rd_string(r, &v->user_properties))) return rc;
    if ((rc = rd_u32(r, &v->display_width))) return rc;
    if ((rc = rd_u32(r, &v->display_height))) return rc;
    return WW_OK;
}

static void free_renderer_init(waywallen_renderer_init_t *v) {
    free_kv_list(&v->settings);
    free(v->user_properties); v->user_properties = NULL;
}

void waywallen_renderer_init_free(waywallen_renderer_init_t *value) {
    if (!value) return;
    free_renderer_init(value);
    memset(value, 0, sizeof(*value));
}

static int w_rgba_color(ww_buf_t *b, const waywallen_rgba_color_t *v) {
    int rc;
    if ((rc = w_f32(b, v->r))) return rc;
    if ((rc = w_f32(b, v->g))) return rc;
    if ((rc = w_f32(b, v->b))) return rc;
    if ((rc = w_f32(b, v->a))) return rc;
    return WW_OK;
}

static int rd_rgba_color(ww_rd_t *r, waywallen_rgba_color_t *v) {
    int rc;
    if ((rc = rd_f32(r, &v->r))) return rc;
    if ((rc = rd_f32(r, &v->g))) return rc;
    if ((rc = rd_f32(r, &v->b))) return rc;
    if ((rc = rd_f32(r, &v->a))) return rc;
    return WW_OK;
}

static void free_rgba_color(waywallen_rgba_color_t *v) {
    (void)v;
}

void waywallen_rgba_color_free(waywallen_rgba_color_t *value) {
    if (!value) return;
    free_rgba_color(value);
    memset(value, 0, sizeof(*value));
}

static int w_renderer_state(ww_buf_t *b, const waywallen_renderer_state_t *v) {
    int rc;
    if ((rc = w_u32(b, v->fields))) return rc;
    if ((rc = w_rgba_color(b, &v->clear_color))) return rc;
    if ((rc = w_kv_list(b, &v->runtime_tags))) return rc;
    return WW_OK;
}

static int rd_renderer_state(ww_rd_t *r, waywallen_renderer_state_t *v) {
    int rc;
    if ((rc = rd_u32(r, &v->fields))) return rc;
    if ((rc = rd_rgba_color(r, &v->clear_color))) return rc;
    if ((rc = rd_kv_list(r, &v->runtime_tags))) return rc;
    return WW_OK;
}

static void free_renderer_state(waywallen_renderer_state_t *v) {
    free_rgba_color(&v->clear_color);
    free_kv_list(&v->runtime_tags);
}

void waywallen_renderer_state_free(waywallen_renderer_state_t *value) {
    if (!value) return;
    free_renderer_state(value);
    memset(value, 0, sizeof(*value));
}

int ww_evt_in_init_encode(const ww_evt_in_init_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_renderer_init(out, &m->config))) return rc;
    return WW_OK;
}

int ww_evt_in_init_decode(const uint8_t *buf, size_t len, ww_evt_in_init_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_renderer_init(&r, &out->config))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_init_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_init_free(out);
    return rc;
}

void ww_evt_in_init_free(ww_evt_in_init_t *m) {
    free_renderer_init(&m->config);
}

uint32_t ww_evt_in_init_expected_fds(const ww_evt_in_init_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_setting_changed_encode(const ww_evt_in_setting_changed_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_kv_list(out, &m->settings))) return rc;
    return WW_OK;
}

int ww_evt_in_setting_changed_decode(const uint8_t *buf, size_t len, ww_evt_in_setting_changed_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_kv_list(&r, &out->settings))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_setting_changed_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_setting_changed_free(out);
    return rc;
}

void ww_evt_in_setting_changed_free(ww_evt_in_setting_changed_t *m) {
    free_kv_list(&m->settings);
}

uint32_t ww_evt_in_setting_changed_expected_fds(const ww_evt_in_setting_changed_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_play_encode(const ww_evt_in_play_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_control_transition(out, &m->transition))) return rc;
    return WW_OK;
}

int ww_evt_in_play_decode(const uint8_t *buf, size_t len, ww_evt_in_play_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_control_transition(&r, &out->transition))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_play_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_play_free(out);
    return rc;
}

void ww_evt_in_play_free(ww_evt_in_play_t *m) {
    free_control_transition(&m->transition);
}

uint32_t ww_evt_in_play_expected_fds(const ww_evt_in_play_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_pause_encode(const ww_evt_in_pause_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_control_transition(out, &m->transition))) return rc;
    return WW_OK;
}

int ww_evt_in_pause_decode(const uint8_t *buf, size_t len, ww_evt_in_pause_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_control_transition(&r, &out->transition))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_pause_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_pause_free(out);
    return rc;
}

void ww_evt_in_pause_free(ww_evt_in_pause_t *m) {
    free_control_transition(&m->transition);
}

uint32_t ww_evt_in_pause_expected_fds(const ww_evt_in_pause_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_pointer_motion_encode(const ww_evt_in_pointer_motion_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_pointer_motion(out, &m->event))) return rc;
    return WW_OK;
}

int ww_evt_in_pointer_motion_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_motion_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_pointer_motion(&r, &out->event))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_pointer_motion_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_pointer_motion_free(out);
    return rc;
}

void ww_evt_in_pointer_motion_free(ww_evt_in_pointer_motion_t *m) {
    free_pointer_motion(&m->event);
}

uint32_t ww_evt_in_pointer_motion_expected_fds(const ww_evt_in_pointer_motion_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_shutdown_encode(const ww_evt_in_shutdown_t *m, ww_buf_t *out) {
    (void)m; (void)out;
    return WW_OK;
}

int ww_evt_in_shutdown_decode(const uint8_t *buf, size_t len, ww_evt_in_shutdown_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    (void)r;
    if (r.pos != r.len) {
        /* empty message; no allocations to release */
        return WW_ERR_TRAILING;
    }
    return WW_OK;
}

void ww_evt_in_shutdown_free(ww_evt_in_shutdown_t *m) {
    (void)m;
}

uint32_t ww_evt_in_shutdown_expected_fds(const ww_evt_in_shutdown_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_negotiate_buffers_encode(const ww_evt_in_negotiate_buffers_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_buffer_directive(out, &m->directive))) return rc;
    return WW_OK;
}

int ww_evt_in_negotiate_buffers_decode(const uint8_t *buf, size_t len, ww_evt_in_negotiate_buffers_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_buffer_directive(&r, &out->directive))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_negotiate_buffers_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_negotiate_buffers_free(out);
    return rc;
}

void ww_evt_in_negotiate_buffers_free(ww_evt_in_negotiate_buffers_t *m) {
    free_buffer_directive(&m->directive);
}

uint32_t ww_evt_in_negotiate_buffers_expected_fds(const ww_evt_in_negotiate_buffers_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_pointer_button_encode(const ww_evt_in_pointer_button_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_pointer_button(out, &m->event))) return rc;
    return WW_OK;
}

int ww_evt_in_pointer_button_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_button_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_pointer_button(&r, &out->event))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_pointer_button_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_pointer_button_free(out);
    return rc;
}

void ww_evt_in_pointer_button_free(ww_evt_in_pointer_button_t *m) {
    free_pointer_button(&m->event);
}

uint32_t ww_evt_in_pointer_button_expected_fds(const ww_evt_in_pointer_button_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_pointer_axis_encode(const ww_evt_in_pointer_axis_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_pointer_axis(out, &m->event))) return rc;
    return WW_OK;
}

int ww_evt_in_pointer_axis_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_axis_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_pointer_axis(&r, &out->event))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_pointer_axis_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_pointer_axis_free(out);
    return rc;
}

void ww_evt_in_pointer_axis_free(ww_evt_in_pointer_axis_t *m) {
    free_pointer_axis(&m->event);
}

uint32_t ww_evt_in_pointer_axis_expected_fds(const ww_evt_in_pointer_axis_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_mute_encode(const ww_evt_in_mute_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_control_transition(out, &m->transition))) return rc;
    return WW_OK;
}

int ww_evt_in_mute_decode(const uint8_t *buf, size_t len, ww_evt_in_mute_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_control_transition(&r, &out->transition))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_mute_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_mute_free(out);
    return rc;
}

void ww_evt_in_mute_free(ww_evt_in_mute_t *m) {
    free_control_transition(&m->transition);
}

uint32_t ww_evt_in_mute_expected_fds(const ww_evt_in_mute_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_unmute_encode(const ww_evt_in_unmute_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_control_transition(out, &m->transition))) return rc;
    return WW_OK;
}

int ww_evt_in_unmute_decode(const uint8_t *buf, size_t len, ww_evt_in_unmute_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_control_transition(&r, &out->transition))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_unmute_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_unmute_free(out);
    return rc;
}

void ww_evt_in_unmute_free(ww_evt_in_unmute_t *m) {
    free_control_transition(&m->transition);
}

uint32_t ww_evt_in_unmute_expected_fds(const ww_evt_in_unmute_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_mpris_encode(const ww_evt_in_mpris_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_mpris_snapshot(out, &m->snapshot))) return rc;
    return WW_OK;
}

int ww_evt_in_mpris_decode(const uint8_t *buf, size_t len, ww_evt_in_mpris_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_mpris_snapshot(&r, &out->snapshot))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_mpris_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_mpris_free(out);
    return rc;
}

void ww_evt_in_mpris_free(ww_evt_in_mpris_t *m) {
    free_mpris_snapshot(&m->snapshot);
}

uint32_t ww_evt_in_mpris_expected_fds(const ww_evt_in_mpris_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_event_subscriptions_applied_encode(const ww_evt_in_event_subscriptions_applied_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_event_subscription_result(out, &m->result))) return rc;
    return WW_OK;
}

int ww_evt_in_event_subscriptions_applied_decode(const uint8_t *buf, size_t len, ww_evt_in_event_subscriptions_applied_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_event_subscription_result(&r, &out->result))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_event_subscriptions_applied_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_event_subscriptions_applied_free(out);
    return rc;
}

void ww_evt_in_event_subscriptions_applied_free(ww_evt_in_event_subscriptions_applied_t *m) {
    free_event_subscription_result(&m->result);
}

uint32_t ww_evt_in_event_subscriptions_applied_expected_fds(const ww_evt_in_event_subscriptions_applied_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_audio_window_encode(const ww_evt_in_audio_window_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_audio_window(out, &m->window))) return rc;
    return WW_OK;
}

int ww_evt_in_audio_window_decode(const uint8_t *buf, size_t len, ww_evt_in_audio_window_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_audio_window(&r, &out->window))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_audio_window_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_audio_window_free(out);
    return rc;
}

void ww_evt_in_audio_window_free(ww_evt_in_audio_window_t *m) {
    free_audio_window(&m->window);
}

uint32_t ww_evt_in_audio_window_expected_fds(const ww_evt_in_audio_window_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_request_frame_encode(const ww_evt_in_request_frame_t *m, ww_buf_t *out) {
    (void)m; (void)out;
    return WW_OK;
}

int ww_evt_in_request_frame_decode(const uint8_t *buf, size_t len, ww_evt_in_request_frame_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    (void)r;
    if (r.pos != r.len) {
        /* empty message; no allocations to release */
        return WW_ERR_TRAILING;
    }
    return WW_OK;
}

void ww_evt_in_request_frame_free(ww_evt_in_request_frame_t *m) {
    (void)m;
}

uint32_t ww_evt_in_request_frame_expected_fds(const ww_evt_in_request_frame_t *m) {
    (void)m;
    return 0;
}

int ww_evt_in_set_log_level_encode(const ww_evt_in_set_log_level_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_log_level(out, m->level))) return rc;
    return WW_OK;
}

int ww_evt_in_set_log_level_decode(const uint8_t *buf, size_t len, ww_evt_in_set_log_level_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_log_level(&r, &out->level))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_in_set_log_level_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_in_set_log_level_free(out);
    return rc;
}

void ww_evt_in_set_log_level_free(ww_evt_in_set_log_level_t *m) {
    (void)m;
}

uint32_t ww_evt_in_set_log_level_expected_fds(const ww_evt_in_set_log_level_t *m) {
    (void)m;
    return 0;
}

int ww_evt_ready_encode(const ww_evt_ready_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_drm_node(out, &m->drm_node))) return rc;
    return WW_OK;
}

int ww_evt_ready_decode(const uint8_t *buf, size_t len, ww_evt_ready_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_drm_node(&r, &out->drm_node))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_ready_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_ready_free(out);
    return rc;
}

void ww_evt_ready_free(ww_evt_ready_t *m) {
    free_drm_node(&m->drm_node);
}

uint32_t ww_evt_ready_expected_fds(const ww_evt_ready_t *m) {
    (void)m;
    return 0;
}

int ww_evt_bind_buffers_encode(const ww_evt_bind_buffers_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_buffer_pool(out, &m->pool))) return rc;
    return WW_OK;
}

int ww_evt_bind_buffers_decode(const uint8_t *buf, size_t len, ww_evt_bind_buffers_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_buffer_pool(&r, &out->pool))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_bind_buffers_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_bind_buffers_free(out);
    return rc;
}

void ww_evt_bind_buffers_free(ww_evt_bind_buffers_t *m) {
    free_buffer_pool(&m->pool);
}

uint32_t ww_evt_bind_buffers_expected_fds(const ww_evt_bind_buffers_t *m) {
    return (uint32_t)((uint64_t)m->pool.count * (uint64_t)m->pool.format.plane_count);
}

int ww_evt_frame_ready_encode(const ww_evt_frame_ready_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_frame(out, &m->frame))) return rc;
    return WW_OK;
}

int ww_evt_frame_ready_decode(const uint8_t *buf, size_t len, ww_evt_frame_ready_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_frame(&r, &out->frame))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_frame_ready_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_frame_ready_free(out);
    return rc;
}

void ww_evt_frame_ready_free(ww_evt_frame_ready_t *m) {
    free_frame(&m->frame);
}

uint32_t ww_evt_frame_ready_expected_fds(const ww_evt_frame_ready_t *m) {
    (void)m;
    return 1;
}

int ww_evt_error_encode(const ww_evt_error_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_string(out, m->message))) return rc;
    return WW_OK;
}

int ww_evt_error_decode(const uint8_t *buf, size_t len, ww_evt_error_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_string(&r, &out->message))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_error_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_error_free(out);
    return rc;
}

void ww_evt_error_free(ww_evt_error_t *m) {
    free(m->message); m->message = NULL;
}

uint32_t ww_evt_error_expected_fds(const ww_evt_error_t *m) {
    (void)m;
    return 0;
}

int ww_evt_release_syncobj_encode(const ww_evt_release_syncobj_t *m, ww_buf_t *out) {
    (void)m; (void)out;
    return WW_OK;
}

int ww_evt_release_syncobj_decode(const uint8_t *buf, size_t len, ww_evt_release_syncobj_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    (void)r;
    if (r.pos != r.len) {
        /* empty message; no allocations to release */
        return WW_ERR_TRAILING;
    }
    return WW_OK;
}

void ww_evt_release_syncobj_free(ww_evt_release_syncobj_t *m) {
    (void)m;
}

uint32_t ww_evt_release_syncobj_expected_fds(const ww_evt_release_syncobj_t *m) {
    (void)m;
    return 1;
}

int ww_evt_format_caps_encode(const ww_evt_format_caps_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_producer_capabilities(out, &m->capabilities))) return rc;
    return WW_OK;
}

int ww_evt_format_caps_decode(const uint8_t *buf, size_t len, ww_evt_format_caps_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_producer_capabilities(&r, &out->capabilities))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_format_caps_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_format_caps_free(out);
    return rc;
}

void ww_evt_format_caps_free(ww_evt_format_caps_t *m) {
    free_producer_capabilities(&m->capabilities);
}

uint32_t ww_evt_format_caps_expected_fds(const ww_evt_format_caps_t *m) {
    (void)m;
    return 0;
}

int ww_evt_bind_failed_encode(const ww_evt_bind_failed_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_bind_failure(out, &m->failure))) return rc;
    return WW_OK;
}

int ww_evt_bind_failed_decode(const uint8_t *buf, size_t len, ww_evt_bind_failed_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_bind_failure(&r, &out->failure))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_bind_failed_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_bind_failed_free(out);
    return rc;
}

void ww_evt_bind_failed_free(ww_evt_bind_failed_t *m) {
    free_bind_failure(&m->failure);
}

uint32_t ww_evt_bind_failed_expected_fds(const ww_evt_bind_failed_t *m) {
    (void)m;
    return 0;
}

int ww_evt_init_nack_encode(const ww_evt_init_nack_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_init_rejection(out, &m->rejection))) return rc;
    return WW_OK;
}

int ww_evt_init_nack_decode(const uint8_t *buf, size_t len, ww_evt_init_nack_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_init_rejection(&r, &out->rejection))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_init_nack_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_init_nack_free(out);
    return rc;
}

void ww_evt_init_nack_free(ww_evt_init_nack_t *m) {
    free_init_rejection(&m->rejection);
}

uint32_t ww_evt_init_nack_expected_fds(const ww_evt_init_nack_t *m) {
    (void)m;
    return 0;
}

int ww_evt_report_state_encode(const ww_evt_report_state_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_renderer_state(out, &m->state))) return rc;
    return WW_OK;
}

int ww_evt_report_state_decode(const uint8_t *buf, size_t len, ww_evt_report_state_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_renderer_state(&r, &out->state))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_report_state_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_report_state_free(out);
    return rc;
}

void ww_evt_report_state_free(ww_evt_report_state_t *m) {
    free_renderer_state(&m->state);
}

uint32_t ww_evt_report_state_expected_fds(const ww_evt_report_state_t *m) {
    (void)m;
    return 0;
}

int ww_evt_set_event_subscriptions_encode(const ww_evt_set_event_subscriptions_t *m, ww_buf_t *out) {
    int rc;
    (void)m;
    if ((rc = w_event_subscription(out, &m->subscription))) return rc;
    return WW_OK;
}

int ww_evt_set_event_subscriptions_decode(const uint8_t *buf, size_t len, ww_evt_set_event_subscriptions_t *out) {
    memset(out, 0, sizeof(*out));
    ww_rd_t r = { buf, 0, len };
    int rc;
    if ((rc = rd_event_subscription(&r, &out->subscription))) goto fail;
    if (r.pos != r.len) {
        int rc2 = WW_ERR_TRAILING;
        (void)rc2;
        ww_evt_set_event_subscriptions_free(out);
        return WW_ERR_TRAILING;
    }
    return WW_OK;
fail:
    ww_evt_set_event_subscriptions_free(out);
    return rc;
}

void ww_evt_set_event_subscriptions_free(ww_evt_set_event_subscriptions_t *m) {
    free_event_subscription(&m->subscription);
}

uint32_t ww_evt_set_event_subscriptions_expected_fds(const ww_evt_set_event_subscriptions_t *m) {
    (void)m;
    return 0;
}

