//! Rust codegen for a parsed `Protocol`.
//!
//! Output is a single self-contained Rust source file that depends on
//! nothing but `std`. It declares:
//!
//!   - `PROTOCOL_NAME`, `PROTOCOL_VERSION`
//!   - `mod opcode::{request, event}` with `pub const` per message
//!   - `struct Rect` (reused across messages)
//!   - `enum DecodeError`
//!   - `enum Request` + `impl Request` with `opcode`, `expected_fds`,
//!     `encode`, `decode`
//!   - `enum Event` + mirror impl
//!
//! The caller is expected to frame the encoded body with the 4-byte
//! `[u16 opcode][u16 total_length]` header. Generated `encode` only
//! writes the body; `decode` only consumes the body. Ancillary fds are
//! passed out-of-band by the codec layer.

use crate::parser::{ArgType, FdSpec, Message, Protocol};
use std::fmt::Write;

pub fn emit(p: &Protocol) -> String {
    let mut out = String::new();
    emit_header(&mut out, p);
    emit_consts(&mut out, p);
    emit_common_types(&mut out);
    emit_wire_helpers(&mut out);
    emit_enum(&mut out, "Request", &p.requests, "request");
    emit_enum(&mut out, "Event", &p.events, "event");
    out
}

fn emit_header(out: &mut String, p: &Protocol) {
    writeln!(out, "// AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND.").unwrap();
    writeln!(out, "// Source: protocol/{}_v{}.xml", p.name, p.version).unwrap();
    writeln!(out).unwrap();
}

fn emit_consts(out: &mut String, p: &Protocol) {
    writeln!(out, "pub const PROTOCOL_NAME: &str = \"{}-v{}\";", p.name.replace('_', "-"), p.version).unwrap();
    writeln!(out, "pub const PROTOCOL_VERSION: u32 = {};", p.version).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub mod opcode {{").unwrap();
    writeln!(out, "    pub mod request {{").unwrap();
    for m in &p.requests {
        writeln!(out, "        pub const {}: u16 = {};", m.name.to_uppercase(), m.opcode).unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    pub mod event {{").unwrap();
    for m in &p.events {
        writeln!(out, "        pub const {}: u16 = {};", m.name.to_uppercase(), m.opcode).unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_common_types(out: &mut String) {
    out.push_str(
        r#"#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Rect {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum DecodeError {
    TooShort,
    BadString,
    BadArrayLen,
    Trailing,
    UnknownOpcode(u16),
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooShort => write!(f, "message body too short"),
            Self::BadString => write!(f, "malformed string"),
            Self::BadArrayLen => write!(f, "array length overflow"),
            Self::Trailing => write!(f, "trailing bytes after decode"),
            Self::UnknownOpcode(op) => write!(f, "unknown opcode {op}"),
        }
    }
}

impl std::error::Error for DecodeError {}

"#,
    );
}

fn emit_wire_helpers(out: &mut String) {
    out.push_str(
        r#"mod wire {
    use super::{DecodeError, Rect};

    // ---- writers ----
    pub fn w_u32(buf: &mut Vec<u8>, v: u32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_i32(buf: &mut Vec<u8>, v: i32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_u64(buf: &mut Vec<u8>, v: u64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_i64(buf: &mut Vec<u8>, v: i64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_f32(buf: &mut Vec<u8>, v: f32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_f64(buf: &mut Vec<u8>, v: f64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_rect(buf: &mut Vec<u8>, r: &Rect) {
        w_f32(buf, r.x); w_f32(buf, r.y); w_f32(buf, r.w); w_f32(buf, r.h);
    }
    pub fn pad4(buf: &mut Vec<u8>) {
        while buf.len() % 4 != 0 { buf.push(0); }
    }
    pub fn w_string(buf: &mut Vec<u8>, s: &str) {
        let len = s.len() as u32 + 1;
        w_u32(buf, len);
        buf.extend_from_slice(s.as_bytes());
        buf.push(0);
        pad4(buf);
    }
    pub fn w_array_u32(buf: &mut Vec<u8>, xs: &[u32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_u32(buf, *v); }
    }
    pub fn w_array_i32(buf: &mut Vec<u8>, xs: &[i32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_i32(buf, *v); }
    }
    pub fn w_array_u64(buf: &mut Vec<u8>, xs: &[u64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_u64(buf, *v); }
    }
    pub fn w_array_i64(buf: &mut Vec<u8>, xs: &[i64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_i64(buf, *v); }
    }
    pub fn w_array_f32(buf: &mut Vec<u8>, xs: &[f32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_f32(buf, *v); }
    }
    pub fn w_array_f64(buf: &mut Vec<u8>, xs: &[f64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_f64(buf, *v); }
    }
    pub fn w_array_string(buf: &mut Vec<u8>, xs: &[String]) {
        w_u32(buf, xs.len() as u32);
        for s in xs { w_string(buf, s); }
    }
    pub fn w_kv_list(buf: &mut Vec<u8>, xs: &[(String, String)]) {
        w_u32(buf, xs.len() as u32);
        for (k, v) in xs {
            w_string(buf, k);
            w_string(buf, v);
        }
    }

    // ---- reader ----
    pub struct R<'a> { buf: &'a [u8], pos: usize }
    impl<'a> R<'a> {
        pub fn new(buf: &'a [u8]) -> Self { Self { buf, pos: 0 } }
        pub fn at_end(&self) -> bool { self.pos == self.buf.len() }
        fn take(&mut self, n: usize) -> Result<&'a [u8], DecodeError> {
            if self.buf.len() - self.pos < n { return Err(DecodeError::TooShort); }
            let out = &self.buf[self.pos..self.pos + n];
            self.pos += n;
            Ok(out)
        }
        pub fn u32(&mut self) -> Result<u32, DecodeError> {
            Ok(u32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn i32(&mut self) -> Result<i32, DecodeError> {
            Ok(i32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn u64(&mut self) -> Result<u64, DecodeError> {
            Ok(u64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn i64(&mut self) -> Result<i64, DecodeError> {
            Ok(i64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn f32(&mut self) -> Result<f32, DecodeError> {
            Ok(f32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn f64(&mut self) -> Result<f64, DecodeError> {
            Ok(f64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn rect(&mut self) -> Result<Rect, DecodeError> {
            Ok(Rect { x: self.f32()?, y: self.f32()?, w: self.f32()?, h: self.f32()? })
        }
        pub fn string(&mut self) -> Result<String, DecodeError> {
            let len = self.u32()? as usize;
            if len == 0 { return Err(DecodeError::BadString); }
            let padded = (len + 3) & !3;
            let bytes = self.take(padded)?;
            if bytes[len - 1] != 0 { return Err(DecodeError::BadString); }
            std::str::from_utf8(&bytes[..len - 1])
                .map(|s| s.to_string())
                .map_err(|_| DecodeError::BadString)
        }
        pub fn array_u32(&mut self) -> Result<Vec<u32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.u32()?); }
            Ok(v)
        }
        pub fn array_i32(&mut self) -> Result<Vec<i32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.i32()?); }
            Ok(v)
        }
        pub fn array_u64(&mut self) -> Result<Vec<u64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.u64()?); }
            Ok(v)
        }
        pub fn array_i64(&mut self) -> Result<Vec<i64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.i64()?); }
            Ok(v)
        }
        pub fn array_f32(&mut self) -> Result<Vec<f32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.f32()?); }
            Ok(v)
        }
        pub fn array_f64(&mut self) -> Result<Vec<f64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.f64()?); }
            Ok(v)
        }
        pub fn array_string(&mut self) -> Result<Vec<String>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(64));
            for _ in 0..n { v.push(self.string()?); }
            Ok(v)
        }
        pub fn kv_list(&mut self) -> Result<Vec<(String, String)>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(64));
            for _ in 0..n {
                let k = self.string()?;
                let val = self.string()?;
                v.push((k, val));
            }
            Ok(v)
        }
    }
}

"#,
    );
}

fn emit_enum(out: &mut String, enum_name: &str, msgs: &[Message], opcode_mod: &str) {
    // enum declaration
    writeln!(out, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(out, "pub enum {enum_name} {{").unwrap();
    for m in msgs {
        let variant = snake_to_camel(&m.name);
        if m.args.is_empty() {
            writeln!(out, "    {variant},").unwrap();
        } else {
            writeln!(out, "    {variant} {{").unwrap();
            for a in &m.args {
                writeln!(out, "        {}: {},", field_name(&a.name), rust_type(&a.ty)).unwrap();
            }
            writeln!(out, "    }},").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // impl
    writeln!(out, "impl {enum_name} {{").unwrap();

    // opcode()
    writeln!(out, "    pub fn opcode(&self) -> u16 {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for m in msgs {
        let variant = snake_to_camel(&m.name);
        let pat = if m.args.is_empty() {
            format!("Self::{variant}")
        } else {
            format!("Self::{variant} {{ .. }}")
        };
        writeln!(out, "            {pat} => opcode::{opcode_mod}::{},", m.name.to_uppercase()).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // expected_fds()
    writeln!(out, "    pub fn expected_fds(&self) -> u32 {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for m in msgs {
        let variant = snake_to_camel(&m.name);
        match &m.fds {
            FdSpec::None => {
                let pat = if m.args.is_empty() {
                    format!("Self::{variant}")
                } else {
                    format!("Self::{variant} {{ .. }}")
                };
                writeln!(out, "            {pat} => 0,").unwrap();
            }
            FdSpec::Fixed(n) => {
                let pat = if m.args.is_empty() {
                    format!("Self::{variant}")
                } else {
                    format!("Self::{variant} {{ .. }}")
                };
                writeln!(out, "            {pat} => {n},").unwrap();
            }
            FdSpec::Product(fields) => {
                // Build a destructure binding each referenced field.
                let fs: Vec<String> = fields.iter().map(|f| field_name(f)).collect();
                let bindings = fs.join(", ");
                writeln!(
                    out,
                    "            Self::{variant} {{ {bindings}, .. }} => ({}) as u32,",
                    fs.iter().map(|f| format!("*{f} as u64")).collect::<Vec<_>>().join(" * ")
                )
                .unwrap();
            }
        }
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // encode()
    writeln!(out, "    pub fn encode(&self, buf: &mut Vec<u8>) {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for m in msgs {
        let variant = snake_to_camel(&m.name);
        if m.args.is_empty() {
            writeln!(out, "            Self::{variant} => {{}}").unwrap();
            continue;
        }
        let bindings: Vec<String> = m.args.iter().map(|a| field_name(&a.name)).collect();
        writeln!(out, "            Self::{variant} {{ {} }} => {{", bindings.join(", ")).unwrap();
        for a in &m.args {
            emit_encode_arg(out, "                ", &field_name(&a.name), &a.ty);
        }
        writeln!(out, "            }}").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // decode()
    writeln!(
        out,
        "    pub fn decode(opcode: u16, body: &[u8]) -> Result<Self, DecodeError> {{"
    )
    .unwrap();
    writeln!(out, "        let mut r = wire::R::new(body);").unwrap();
    writeln!(out, "        let v = match opcode {{").unwrap();
    for m in msgs {
        let variant = snake_to_camel(&m.name);
        writeln!(out, "            opcode::{opcode_mod}::{} => {{", m.name.to_uppercase()).unwrap();
        if m.args.is_empty() {
            writeln!(out, "                Self::{variant}").unwrap();
        } else {
            for a in &m.args {
                emit_decode_arg(out, "                ", &field_name(&a.name), &a.ty);
            }
            writeln!(out, "                Self::{variant} {{").unwrap();
            for a in &m.args {
                writeln!(out, "                    {},", field_name(&a.name)).unwrap();
            }
            writeln!(out, "                }}").unwrap();
        }
        writeln!(out, "            }}").unwrap();
    }
    writeln!(out, "            other => return Err(DecodeError::UnknownOpcode(other)),").unwrap();
    writeln!(out, "        }};").unwrap();
    writeln!(out, "        if !r.at_end() {{ return Err(DecodeError::Trailing); }}").unwrap();
    writeln!(out, "        Ok(v)").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_encode_arg(out: &mut String, indent: &str, name: &str, ty: &ArgType) {
    match ty {
        ArgType::U32 => writeln!(out, "{indent}wire::w_u32(buf, *{name});").unwrap(),
        ArgType::I32 => writeln!(out, "{indent}wire::w_i32(buf, *{name});").unwrap(),
        ArgType::U64 => writeln!(out, "{indent}wire::w_u64(buf, *{name});").unwrap(),
        ArgType::I64 => writeln!(out, "{indent}wire::w_i64(buf, *{name});").unwrap(),
        ArgType::F32 => writeln!(out, "{indent}wire::w_f32(buf, *{name});").unwrap(),
        ArgType::F64 => writeln!(out, "{indent}wire::w_f64(buf, *{name});").unwrap(),
        ArgType::Rect => writeln!(out, "{indent}wire::w_rect(buf, {name});").unwrap(),
        ArgType::String => writeln!(out, "{indent}wire::w_string(buf, {name});").unwrap(),
        ArgType::KvList => writeln!(out, "{indent}wire::w_kv_list(buf, {name});").unwrap(),
        ArgType::Array(elem) => {
            let fn_suffix = match **elem {
                ArgType::U32 => "u32",
                ArgType::I32 => "i32",
                ArgType::U64 => "u64",
                ArgType::I64 => "i64",
                ArgType::F32 => "f32",
                ArgType::F64 => "f64",
                ArgType::String => "string",
                _ => panic!("unsupported array element"),
            };
            writeln!(out, "{indent}wire::w_array_{fn_suffix}(buf, {name});").unwrap();
        }
    }
}

fn emit_decode_arg(out: &mut String, indent: &str, name: &str, ty: &ArgType) {
    let expr = match ty {
        ArgType::U32 => "r.u32()?".to_string(),
        ArgType::I32 => "r.i32()?".to_string(),
        ArgType::U64 => "r.u64()?".to_string(),
        ArgType::I64 => "r.i64()?".to_string(),
        ArgType::F32 => "r.f32()?".to_string(),
        ArgType::F64 => "r.f64()?".to_string(),
        ArgType::Rect => "r.rect()?".to_string(),
        ArgType::String => "r.string()?".to_string(),
        ArgType::KvList => "r.kv_list()?".to_string(),
        ArgType::Array(elem) => {
            let suffix = match **elem {
                ArgType::U32 => "u32",
                ArgType::I32 => "i32",
                ArgType::U64 => "u64",
                ArgType::I64 => "i64",
                ArgType::F32 => "f32",
                ArgType::F64 => "f64",
                ArgType::String => "string",
                _ => panic!("unsupported array element"),
            };
            format!("r.array_{suffix}()?")
        }
    };
    writeln!(out, "{indent}let {name} = {expr};").unwrap();
}

fn rust_type(ty: &ArgType) -> String {
    match ty {
        ArgType::U32 => "u32".into(),
        ArgType::I32 => "i32".into(),
        ArgType::U64 => "u64".into(),
        ArgType::I64 => "i64".into(),
        ArgType::F32 => "f32".into(),
        ArgType::F64 => "f64".into(),
        ArgType::String => "String".into(),
        ArgType::Rect => "Rect".into(),
        ArgType::KvList => "Vec<(String, String)>".into(),
        ArgType::Array(elem) => format!("Vec<{}>", rust_type(elem)),
    }
}

fn snake_to_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = true;
    for c in s.chars() {
        if c == '_' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

// Rust reserved keywords that might collide with protocol arg names.
fn field_name(raw: &str) -> String {
    match raw {
        "type" | "ref" | "move" | "match" | "self" | "super" | "where" | "box" => format!("r#{raw}"),
        _ => raw.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel() {
        assert_eq!(snake_to_camel("hello"), "Hello");
        assert_eq!(snake_to_camel("register_display"), "RegisterDisplay");
        assert_eq!(snake_to_camel("frame_ready"), "FrameReady");
    }

    #[test]
    fn rust_type_basic() {
        assert_eq!(rust_type(&ArgType::U32), "u32");
        assert_eq!(rust_type(&ArgType::String), "String");
        assert_eq!(rust_type(&ArgType::Array(Box::new(ArgType::U32))), "Vec<u32>");
        assert_eq!(rust_type(&ArgType::Array(Box::new(ArgType::String))), "Vec<String>");
        assert_eq!(rust_type(&ArgType::KvList), "Vec<(String, String)>");
        assert_eq!(rust_type(&ArgType::Rect), "Rect");
    }
}
